### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by hadley** [Tazinho/Advanced-R-Solutions#1]
This looks great. Can I "bless" this solution set in some way?

**Comment by Tazinho** [comment]
Thanks for your compliment! We are really happy that you found and like it.
Anyhow, we apologize, that we didn't ask for your "blessing" first!
You would indeed do us a great favour. Any kind of statement that shows your agreement (maybe a tweet or a link in the textbook, ...) should help us to feel more "legal".

**Comment by hadley** [comment]
I'll tweet about it shortly.

I can't promise I have much time regularly, but feel free to at-mention in pull request if you'd like to get my feedback.

**Comment by hadley** [comment]
Do you have a twitter username I can credit?

**Comment by Tazinho** [comment]
Sure! @Tazmaaan & @henningsway. Thank you
