### ISSUE TITLE
[Edit] - "Subsetting"-Chapter

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#100]
@Tazinho 
- [x] Sync subsection names
- [x] Ensure that exercise numbers go 1,2,3,.. in each subsection.
- [x] Ensure linebreaks between Q & As
- [x] Sync the text and the order of all exercises in the chapter between Adv R and Adv R Solutions.

Read through all exercises. Edit them if possible and mark their correct status (green = "think this solution is correct", orange = "this solution is definitely not correct or sth. is missing". If sth. is missing, try to includede a todo). Also document open points within the following checklist:
- [x] [Selecting multiple arguments](https://advanced-r-solutions.rbind.io/subsetting.html#selecting-multiple-arguments)
  - [x] (3): Need to mention why the output is an atomic and not a matrix again in a bit more detail. Maybe also include an extra code chunk showing the results.
  @Tazinho (to me the answer looks fine, could you tell me in a little more detail, what you would like to have added?)
  - My comment was a bit confusing. However, the answer wasn't answering the whole part of the question and also not really providing all the relevant information. Changed it.
  - [x] (4): Need to read through it again and pay close attention to the wording.
  - [x] (5): Needs to be shortened
  @Tazinho pheeewww. I don't even see the key elements of the answer right now. Could take some time, maybe we should talk about this one later on.
- [x] [Selecting a single element](https://advanced-r-solutions.rbind.io/subsetting.html#selecting-a-single-element)
  - [ ] (1): We could possibly crowdsource this, to get even more solutions. :)
  - Yes, but then we should not evaluate every line. It takes a bit much space already ;-)
  - [x] (2): The solution doesn't exactly correspond to the exercise text. Also the code comments in this exercise might fit better on the conent for the exercise above.
- [x] [Applications](https://advanced-r-solutions.rbind.io/subsetting.html#applications)
  - [x] (2): Reformulate a bit for a "better appearance" (i.e. break the code chunk)

- [x] All open points/exercises should now be reported explicitly under each bullet point above (maybe henningsway can solve one or the other, has a good idea for a new approach or has a more specific question to raise in an issue to Hadley. 

- [x] Assign Henningsway

@henningsway 
- [x] Read & edit all exercises.
- [x] Report any new points while updating the list above. 
- [x] Run a final spellcheck

@Tazinho and @henningsway 
- [x] Try to resolve any of the reported issues above.

**Comment by henningsway** [comment]
Hey @Tazinho,
could you let me know, once you have done the "initial editing" for this chapter and assign me? :)

**Comment by Tazinho** [comment]
Sure

**Comment by henningsway** [comment]
yes, this is absolutely fine! (I just need to know, when it is reasonable to start my review part.) :)

**Comment by henningsway** [comment]
Alright, I am happy with this chapter for now. @Tazinho could you check it once more and then close here? :)

**Comment by Tazinho** [comment]
Last commit didn’t build succesfully. Will link into it the next days...
