### ISSUE TITLE
[Solve] - "Function factories"-Chapter

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#103]
### [Factory fundamentals](https://advanced-r-solutions.rbind.io/function-factories.html#factory-fundamentals)

- [x] 1. The definition of force() is simple:....
- [x] 2. Base R contains two function factories, approxfun() and ecdf(). Read their ...
- [x] 3. Create a function pick() that takes an index, i, as an argument and returns a function...
- [x] 4. Create a function that creates functions that compute the ith central moment of a numeric...
- [x] 5. What happens if you don’t use a closure? Make predictions, then verify with the code ...
- [x] 6. What happens if you use <- instead of <<-? Make predictions, then verify with the code...

### [Graphical factories](https://advanced-r-solutions.rbind.io/function-factories.html#graphical-factories)
- [ ] 1. Compare and contrast ggplot2::label_bquote() with scales::number_format()....

### [Statistical factories](https://advanced-r-solutions.rbind.io/function-factories.html#statistical-factories)
- [x] 1. In boot_model(), why don’t I need to force the evaluation of df or model?...
- [ ] 2. Why might you formulate the Box-Cox transformation like this? ...
- [x] 3. Why don’t you need to worry that boot_permute() stores a copy of the data inside the ...
- [ ] 4. How much time does ll_poisson2() save compared to ll_poisson1()? Use ...

### [Function factories + functionals](https://advanced-r-solutions.rbind.io/function-factories.html#functiono-factories+functionals)

- [x] 1. Which of the following commands is equivalent to with(x, f(z))?...
- [ ] 2. Compare and contrast the effects of env_bind() vs. attach() for the following code...

**Comment by dongzhuoer** [comment]
Answer of "The definition of force() is simple"

From `?force`

>  just evaluating the symbol will do the same thing

I guess it makes your intend clear, you *force** the evaluation of some code

**Comment by Tazinho** [comment]
I think three of the final four exercises are relatively hard. I will solve the easy one (benchmarking) and close here afterwards. Maybe we can resolve the harder ones together during the editing phase.
