### ISSUE TITLE
[Edit] - "Functionals"-Chapter

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#105]
@Tazinho 
- [x] Sync subsection names
- [x] Ensure that exercise numbers go 1,2,3,.. in each subsection.
- [x] Ensure linebreaks between Q & As
- [x] Sync the text and the order of all exercises in the chapter between Adv R and Adv R Solutions.

Read through all exercises. Edit them if possible and mark their correct status (green = "think this solution is correct", orange = "this solution is definitely not correct or sth. is missing". If sth. is missing, try to includede a todo). Also document open points within the following checklist:

### [My first functional: map()](https://advanced-r-solutions.rbind.io/functionals.html#my-first-functional:-map)

- [x] 1. Use as_mapper() to explore how purrr generates anonymous functions for the integer, ...
  - [x] Nr. 1: Not solved yet.
- [x] 2. map(1:3, ~ runif(2)) is a useful pattern for generating random numbers, but ...
- [x] 3. Use the appropriate map() function to: ...
- [x] 4. The following code simulates the performance of a t-test for non-normal data. Extract ...
- [x] 5. The following code uses a map nested inside another map to apply a function to every...
- [x] 6. Use map() to fit linear models to the mtcars using the formulas stored in this list:
- [x] 7. Fit the model mpg ~ disp to each of the bootstrap replicates of mtcars in the list ...
  - [x] Nr. 7: The math symbols ($R^2$) aren't shown correctly in our book (see screenshot). Maybe we are missing mathjax in the build progress? (There was also a [similar issue](https://github.com/hadley/adv-r/issues/1391) in Adv R.) 
![grafik](https://user-images.githubusercontent.com/11295192/50546886-b1f30200-0c2f-11e9-91ae-5f9575def26b.png)

### [Map variants](https://advanced-r-solutions.rbind.io/functionals.html#map-variants)
- [x] 1. Explain the results of modify(mtcars, 1). ...
- [x] 2. Rewrite the following code to use iwalk() instead of walk2(). What are the  ...
- [x] 3. Explain how the following code transforms a data frame using functions stored in a list. ...
- [x] 4. What does write.csv() return? i.e. what happens if you use it with map2() instead of ...

### [Predicate functionals](https://advanced-r-solutions.rbind.io/functionals.html#predicate-functionals)
- [x] 1. Why isn’t is.na() a predicate function? What base R function is closest to being a ...
- [x] 2. simple_reduce() has a problem when x is length 0 or length 1. Describe the source ...
- [x] 3. Implement the span() function from Haskell: given a list x and a predicate function ...
- [x] 4. Implement arg_max(). It should take a function and a vector of inputs, and return the ...
- [x] 5. The function below scales a vector so it falls in the range [0, 1]. How would you apply ...

### [Base functionals](https://advanced-r-solutions.rbind.io/functionals.html#base-functionals)
- [x] 1. How does apply() arrange the output? Read the documentation and perform some ...
- [x] 2. What do eapply() and rapply() do? Does purrr have equivalents? ...
- [x] 3. Challenge: read about the fixed point algorithm. Complete the exercises using R ...
  - [x] Nr. 3: Not solved yet.

- [x] All open points/exercises should now be reported explicitly under each bullet point above (maybe henningsway can solve one or the other, has a good idea for a new approach or has a more specific question to raise in an issue to Hadley. 

- [x] Assign Henningsway

@henningsway 
- [x] Read & edit all exercises.
- [x] Report any new points while updating the list above. 
- [x] Run a final spellcheck

@Tazinho and @henningsway 
- [x] Try to resolve any of the reported issues above.

**Comment by Tazinho** [comment]
@henningsway These exercises were pretty straight forward. In my eyes it would make sense, if you go once over it, as they should be understandable and most just need improved formulations. Hope thats ok!?

**Comment by Tazinho** [comment]
@henningsway Can you check out, if this chapter can be edited relatively easy? I think my "default english" in this chapter is better than in the conditions chapter, so it might make sense if you look over it anyway and I think (read "hope") this could be a "quick win".

**Comment by henningsway** [comment]
@Tazinho 

I just finished editing this chapter. There is three longish exercises, which I would like you to take another look at. (Map variants 3, Predicate functionals 3, Base functionals 1)

If necessary, I could look at them again or you could pass it up to hadley for review after.

**Comment by Tazinho** [comment]
I can do it. Will take some time though

**Comment by henningsway** [comment]
Nice :)
