### ISSUE TITLE
link broken in 2-07-Functionals.Rmd

### ISSUE THREAD

**Issue by dongzhuoer** [Tazinho/Advanced-R-Solutions#112]
https://github.com/Tazinho/Advanced-R-Solutions/blob/bfc276c086f239ee460b8e0c1128cc986e91f22e/2-07-Functionals.Rmd#L837

**Comment by dongzhuoer** [comment]
![image](https://user-images.githubusercontent.com/15871952/50392423-428d9600-0789-11e9-84a8-ce9764f1f30b.png)

**Comment by dongzhuoer** [comment]
![image](https://user-images.githubusercontent.com/15871952/50392427-4a4d3a80-0789-11e9-8e2c-6318c1857203.png)

**Comment by Tazinho** [comment]
Thanks!
