### ISSUE TITLE
Estimate no. of pages and graphics

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#115]
Will do this after 1st part is finished. Process will be: Convert HTML to PDF -> get average sites and graphics per exercise -> extrapolate this quote for the amount of all exercises.

**Comment by Tazinho** [comment]
Numbers from Advanced R

# 108 #
Names & values 5 | 4 | 3 | 3 = 15
Vectors        5 | 4 | 3 | 3 | 4 = 19
Subsetting     6 | 2 | 3 = 11
Control-flow   2 | 3 = 5
Functions      7 | 3 | 6 | 3 | 5 | 9 = 33
Environments   6 | 2 | 3 | 1 = 12
Conditions     2 | 5 | 2 | 4 = 13

# 40 #
Functionals    7 | 4 | 5 | 3 = 19
Function fact. 6 | 1 | 4 | 2 = 13
Function op.   3 | 5 = 8

# 51 #
S3             6 | 5 | 6 | 2 | 3 | 3 = 25
R6             7 | 4 | 1 = 12
S4             2 | 3 | 4 | 3 | 2 = 14

# 61 #
Expressions    5 | 6 | 10 | 4 = 25
Quasiquotation 2 | 6 | 2 | 3 | 3 = 16
Evaluation     5 | 2 | 3 | 1 | 3 = 14
Translating RC 4 | 2 = 6

# 24 #
Measuring Perf 1 | 2 = 3
Improving Perf 5 | 3 | 3 = 11
CPP            2 | 2 | (6) = 10

284

**Comment by Tazinho** [comment]
Reestimate via tipps in https://yihui.name/en/2018/08/bookdown-crc/ to match a more typical layout etc.

**Comment by henningsway** [comment]
Made some first steps using the template linked above, but I keep running into encoding problems and asked yihui for advice: https://github.com/yihui/bookdown-crc/issues/2

Planning to focus more on editing the next chapters in the meantime.

**Comment by henningsway** [comment]
- [ ] need to consider the proper width of the code chunks (55 vs 80 characters)

(think about impact on page estimation and downstream workflow)

**Comment by henningsway** [comment]
@hadley We are currently trying to get this project to compile to `bookdown::pdf_output()`, ideally using yihuis crc-template or the advanced r preamble for the layout.

Currently it is not yet rendering correctly, which, at this point, seems to boil down to encoding issues: https://github.com/yihui/bookdown-crc/issues/2 Would you have any input on this one?

We are also not sure, what number of characters is feasible for the code chunks. I read Yihui write about a 55character limit for the printed edition, which seems very slim. How do you currently handle this in AdvR?

**Comment by hadley** [comment]
For the line drawing characters you need this hack: https://github.com/hadley/adv-r/blob/master/latex/preamble.tex#L24-L33

I don't remember exactly how I got to this number (except that it involved experimentation) but I use 69 in Adv-R: https://github.com/hadley/adv-r/blob/master/common.R#L30-L31

**Comment by henningsway** [comment]
A few notes to future me from my journey towards a compiling pdf:

- use xelatex (`sudo apt-get install texlive-xetex`)
- set up tlmgr for fonts (`sudo apt-get install xzdec` and `tlmgr init-usertree`)
- install fonts (`tlmgr install collection-fontsrecommended` or `tlmgr install collection-fontsextra`)
- install Andale Mono (`sudo apt-get install msttcorefonts`)

I still miss how to set up Inconsolata on my system (`tlmgr info inconsolata` says, it is installed and `apt-get install texlive-fonts-extra` seems overkill (takes 1Gb))

Will see hot this applies to ARS tomorrow.

**Comment by henningsway** [comment]
We have a first pdf with reasonable formatting. Let's update our estimations and close the issue after.

**Comment by Tazinho** [comment]
Perfect, can u also summarize open points in another issue, i.e. „compile final pdf output“ and write the corresponding e-mail including the current estimation and PDF attached?
