### ISSUE TITLE
Let chapter & section number match the original book

### ISSUE THREAD

**Issue by dongzhuoer** [Tazinho/Advanced-R-Solutions#116]
In [original book](https://adv-r.hadley.nz/)

![image](https://user-images.githubusercontent.com/15871952/50436898-cdee5f00-0922-11e9-8de1-7ff2e0bf5a1c.png)

But in this book

![image](https://user-images.githubusercontent.com/15871952/50436973-08f09280-0923-11e9-9b0b-4a4dbfc65fa5.png)

The inconsistency makes it hard to refer to exercise in issue & PR

**Comment by dongzhuoer** [comment]
Would you consider add empty 1st/2nd level header, like the [answer book](https://jrnold.github.io/r4ds-exercise-solutions) for "R for data science"

![image](https://user-images.githubusercontent.com/15871952/50437075-5ec53a80-0923-11e9-9b49-96a5fa553659.png)

In that book, sections share same number as that of the original book.

**Comment by Tazinho** [comment]
I agree. I will add the empty chapters for the solution process. For the final book we still have to discuss this with the publisher.

**Comment by Tazinho** [comment]
Moved to [Checklist for finalisation](https://github.com/Tazinho/Advanced-R-Solutions/issues/123)
