### ISSUE TITLE
Finalize Book

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#123]
## Adress numberings of Chapters/ Sections/ Exercises
- [x] Chapter numberings should match Advanced Rs chapter numbering in the PDF version
- [[ ]] Chapter numberings should match Advanced Rs chapter numbering in the HTML/bs4_book version (after PDF)

- [x] Subchapter numberings should match Advanced Rs chapter numbering in the PDF version
- [[ ]] Subchapter numberings should match Advanced Rs chapter numbering in the HTML/bs4_book version

- [x] question numberings per subchapter must be in sequential order (starting with 1 in each subchapter)

## Spellcheck
- [x] do initial spellcheck (with MS Word); use British English. If necessary collect most important differences (in our context).
  - I dindn't use "," between two main sentences (sry, my punctuation skills are superbad)
  - I didn't use "," before and/or within enumerations.
  - I left in most of the short forms, i.e. it's, doesn't etc. as it's good for the flow (and also Hadley does it).
  - I didn't change "in order to" to "to", because I think it emphasizes the causation a bit more.
- [x] check that all hyperlinks work (link "directly" to the correct resource) and are properly named
- [x] check that links are correctly formatted (and don't contain unnecessary information (such as ?parameters))
- [x] check via a regular expression if words are duplicated, example "... the the ..."
- [x] use "ise" instead of "ize" for words like optimise, customise etc.
- [x] check it`s vs its
- [x] check every `s (is it correctly genitive)
- [x] check words with dashes (is the dash correct)
- [x] check for unique writings of similar words (eg. dataset vs. data set; reference here is the spelling in Advanced R)
- [x] write for loop only in this way: „for loop“ (i.e. no ticks or hyphen).
- [x] write if condition and while condition
- [x] check that every bracket ("(", "{", "[") in text or inline code is correctly closed
- [x] check that every " and ' in text or in inline code is correctly closed
- [x] check full stop after every sentence, especially in front of code blocks (here mostly full stop or colon).

  - [x] check every `
  - [x] check every codespace within `` and codeblocks if they have brackets
  - [x] make sure that chunks are in inconsolata font

## Code Chunks
- [x] check that indended errors are handled via the chunkoptions (i.e. error=true, warning=true etc) instead of hardcoding or other workarounds
- [x] check that include=FALSE chunk option is only used in extreme corner cases. Especially library calls must be included.
- [x] check that no spurious message/warning messages are part of the book. Should be decision on a chunk-to-chunk basis. (suppress via chunk arguments if necessary)

## Code style
- [x] ensure [tidyverste style guide](https://style.tidyverse.org/) is consistently followed and define most important steps
  - 2 spaces between: function()  {}
  - (at least) two spaces in front of inline comments
  - inline comments may start in lowercase. Comments that have an own line are always starting in uppercase
- [x] check that our error messages and warnings are consistent with the [tidyverste style guide](https://style.tidyverse.org/)
- [x] compare with `styler` recommendations
- [x] check unnecessary code, e.g. 1L:100L (L is not needed here)
- [x] check that code in a for loop always has the following spacing: for (...) {
- [x] check that code in an if statement always has the following spacing: if (...) {
- [x] check that code in a while statement always has the following spacing: while (...) {

## Answer Style
- [x] check that solutions typically start with sentence instead of code
- [x] Further use `class` and `attributes` (backticks) when refering to class and attribute names, see https://github.com/hadley/adv-r/issues/1516
- [x] decide how packages should be mentioned in the text (e.g. **bench** or `{bench}`). Check with C&H / Hadley (Hadley uses in Advanced R just Hyperlinks (+ Citations, when possible), e.g. [purrr package](https://purrr.tidyverse.org) [@purrr] when he first mentions a package within a chapter. Afterwards, he just writes the name of the package without specific formatting.)
- [x] make sure all packages in the text confirm to the chosen convention (`{packagename}`)
- [x] make sure all functions end on `()`. Exceptions: `[`, `[[`, `$`; `&`, `&&`, `|`, `||` and similar infix operators.
- [x] We often use "... , see ?some_function". It is better to use ";" e.g. "... ; see ?some_function".
- [x] If we use italic font, we would have to use it consistently throughout the whole book. Let's discuss this. (Also it looks like italian font isn't used within Advance R at all).
- [x] Use double quotes " instead of single quotes '
- [x] Use correct hyphen: "—" ("em"-.dash) and not "-" (minus)

## Code Reusage
- [x] Source Code from the Advanced R Textbook explicitly (i.e. use chunk option `include=TRUE`) and state in the text that this code is from Advanced R.

## Avoid typical code smells
- [x] check that within `if` statements `||` and `&&` are used to compare length-1 vectors (and not `|` or `&`)
- [x] check that `drop = FALSE` is only used where necessary
- [x] check that `stringsAsFactors` is only used where necessary
- [x] don't use deprecated pkgs, functions or arguments. Just scan the final output for deprecated comments in evaluated code chunks to spot some of these.

## Library calls
- [x] Load libraries in the beginning of a chapter
  - Conventions for loading packages
    - Load packages via `library(package)` at the beginning of the regarding chapter under a separate paragraph: "Prerequisites" and suppress warnings and messages for this chunk via RMarkdown chunk option (`message=FALSE`, `warning=FALSE`)
      - Exception1: Infrequently used packages don't have to be loaded. Instead use explicit `package::function()` notation.
      - Exception2: {magrittr}`and `{ggplot2}` : If it is only needed in one answer, it is OK to load that library within the answer.

## Citations
- [x] Decide in which cases do we cite? Do we cite and where do we cite Advanced R, R Language, Bookdown, Packages used/mentioned throughout the book.

## Copy Right
- [x] Check that we have the CR or do the regarding statements (e.g. we must check or emoji graphic and orient ourself on what Hadley did for this case).

## Formatting
- [x] check that code chunks in lists are similarly indented as the list/bullet points. (compare with exercise 2.1.4). Search for them via - or *.

## Check prerequisites section for all chapters
- [x] avoid introduction of incompatible section numbers between book (maybe use number 0 for every prerequsites section)
- [[optional]] introductory sentence for every chapter

## Remove and Solve TODOs
- [x] check that no more TODO comment or comments by HW/Henning/Malte remain in text.

## Other Formatting
- [x] use `-` for bulleted lists
- [x] Stick to 69 characters margin in code chunks
- [x] Abbreviations need to be introduced: AST, 

## Benchmarks
- [x] run `bench::mark` with `check = TRUE` (only use `check = FALSE` if there is a good reason for it).
- [x] find consistency with mentioning that the exact output of bm depends on the system running the code (not sure what is best here.. it's also not that important..)

## Check all graphics
- [x] https://github.com/Tazinho/Advanced-R-Solutions/issues/256

### Title Cover
- idea: progress chart as representative graphic?
- [x] check with C&H if appropriate
- [x] implement necessary changes

### Testimonials
- [[optional]] collect testimonials that could be used for the book

### Thank all contributors
- [x] mention contributors within the book (can be done now, additional contribution should be mentioned right away)
- [x] also include contributions to the 1st edition (my github API Limit was empty. So, need to do this another day)(The relevant code is in preface.Rmd. Not in index.Rmd)
- [x] check that now Github Contributior is missing: https://github.com/Tazinho/Advanced-R-Solutions/graphs/contributors
- [x] include names from GitHub in addition to handles (similar to Advanced R)

## Update and "Freeze" Software
- [x] Update R Version and packages, if necessary around hand-in date
- [x] avoid development versions where possible
- [x] replace all calls to `devtools::install_github()` with `remotes::install_github()`
- [x] Check that we match all exercise texts again.
  - Done on 08.12.2020

**Comment by henningsway** [comment]
just updated this issue (it got loooong). Let's improve and extend this were necessary, tackle one task after the other efficiently and get it over with. :D

**Comment by Tazinho** [comment]
For a better overview: A copy of open tasks.

When done, let's check them in the starting post and remove them from this post (via editing).

## Adress numberings of Chapters/ Sections/ Exercises
- [ ] Chapter numberings should match Advanced Rs chapter numbering in the HTML/bs4_book version
- [ ] Subchapter numberings should match Advanced Rs chapter numbering in the PDF version
- [ ] Subchapter numberings should match Advanced Rs chapter numbering in the HTML/bs4_book version

## Code Chunks
- [ ] check that indended errors are handled via the chunkoptions (i.e. error=true, warning=true etc) instead of hardcoding or other workarounds
- [ ] check that include=FALSE chunk option is only used in extreme corner cases. Especially library calls must be included.
- [ ] check that no spurious message/warning messages are part of the book. Should be decision on a chunk-to-chunk basis. (suppress via chunk arguments if necessary)

# Code style
- [ ] check that our error messages and warnings are consistent with the [tidyverste style guide](https://style.tidyverse.org/)

## Answer Style
- [ ] decide how packages should be mentioned in the text (e.g. **bench** or `{bench}`). Check with C&H / Hadley
- [ ] make sure all packages in the text confirm to the chosen convention
- [ ] If we use italic font, we would have to use it consistently throughout the whole book. Let's discuss this. (Also it looks like italian font isn't used within Advance R at all).

## Code Reusage
- [ ] Source Code from the Advanced R Textbook explicitly (i.e. use chunk option `include=TRUE`) and state in the text that this code is from Advanced R.

## Avoid typical code smells
- [ ] check that within `if` statements `||` and `&&` are used to compare length-1 vectors (and not `|` or `&`)

## Library calls
- [ ] Load libraries in the beginning of a chapter
  - Conventions for loading packages
    - Load packages via `library(package)` at the beginning of the regarding chapter under a separate paragraph: "Prerequisites" and suppress warnings and messages for this chunk via RMarkdown chunk option (`message=FALSE`, `warning=FALSE`)
      - Exception1: Infrequently used packages don't have to be loaded. Instead use explicit `package::function()` notation.
      - Exception2: {magrittr}`and `{ggplot2}` : If it is only needed in one answer, it is OK to load that library within the answer.

## Citations
- [ ] Decide in which cases do we cite? Do we cite and where do we cite Advanced R, R Language, Bookdown, Packages used/mentioned throughout the book.

## Remaining Questions regarding PDF Formatting
- [[optional]] o we need an extra small vertical space before each question?
  - could be introduced by `\vspace{12pt}`

## Remove and Solve TODOs
- [ ] check that no more TODO comment or comments by HW/Henning/Malte remain in text.

## Other Formatting
- [ ] Stick to 69 characters margin in code chunks

## Benchmarks
- [ ] run `bench::mark` with `check = TRUE` (only use `check = FALSE` if there is a good reason for it).
- [ ] find consistency with mentioning that the exact output of bm depends on the system running the code (not sure what is best here.. it's also not that important..)

## Check all graphics
- [ ] meaningful in the context of the exercise
- [ ] good size
- [ ] good resolution
- [ ] good titles/ labs/ etc
- [ ] good colour choices (colour-blind-friendly?)
- [[optional]] freeze/ screenshot graphics

## Additional Preparations for book
### Title Cover
- idea: progress chart as representative graphic?
- [ ] check with C&H if appropriate
- [ ] implement necessary changes

### Testimonials
- [[optional]] collect testimonials that could be used for the book

### Thank all contributors
- [ ] mention contributors within the book (can be done now, additional contribution should be mentioned right away)
- [ ] also include contributions to the 1st edition
- [ ] check that now Github Contributior is missing: https://github.com/Tazinho/Advanced-R-Solutions/graphs/contributors
- [[optional]] include names from GitHub in addition to handles (similar to Advanced R)

## Update and "Freeze" Software
- [ ] BLOCKED Update R Version and packages, if necessary around hand-in date
- [[optional]] BLOCKED freeze production environment around hand-in date
- [ ] avoid development versions where possible
- [ ] replace all calls to `devtools::install_github()` with `remotes::install_github()`
