### ISSUE TITLE
[Edit] - "Conditions"-Chapter

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#124]
@Tazinho 
- [x] Sync subsection names
- [x] Ensure that exercise numbers go 1,2,3,.. in each subsection.
- [x] Ensure linebreaks between Q & As
- [x] Sync the text and the order of all exercises in the chapter between Adv R and Adv R Solutions.

Read through all exercises. Edit them if possible and mark their correct status (green = "think this solution is correct", orange = "this solution is definitely not correct or sth. is missing". If sth. is missing, try to includede a todo). Also document open points within the following checklist:
- [x] [Signalling conditions](https://advanced-r-solutions.rbind.io/conditions.html#signalling-conditions)
  - [x] Nr. 1
  - [x] Nr. 2: 
    - Unfortunately not really solved yet. Also: Maybe we can find better (less arbitrary) names for the examples...also think about using the info from the footnote on `cat()`
- [x] [Handling conditions](https://advanced-r-solutions.rbind.io/conditions.html#signalling-conditions)
  - [x] Nr. 1: The output might be a little bit long. Also: Why doesn't `catch_cnd()` throw an error (rlang is not loaded in any of the above codechunks!?)
  - [x] Nr. 2: Maybe we can format the comments a bit nicer (Or answer the question within a new code chunk)
  - [x] Nr. 3: @Tazinho could you clarify a little bit more, what is happening in this example? Afterwards, I will improve the prose.
    TBH, after looking at this answer again, I think it is already clear enough.
  - [x] Nr. 4: Improve formulations a bit
  - [x] Nr. 5: Not sure if we need the 2nd part of the answer. (It might become too lengthy).
        @Tazinho could you elaborate a little bit more on, how this works exactly? (1 good sentence or so)
    - Thanks, looks far better without the 2nd part of the answer!
- [x] [Custom conditions](https://advanced-r-solutions.rbind.io/conditions.html#custom-conditions)
  - [x] Nr. 1: Improve forumlations a bit.
  - [x] Nr. 2: Unclear if the solution is correct.
- [x] [Applications](https://advanced-r-solutions.rbind.io/conditions.html#Applications)
  - [x] Nr. 1: From my perspective this one is solved. If Hadley rejects this solutions we might need to ask him about why `dump.frames()` doesn't seem to work as documented. Regarding issue on SO: https://stackoverflow.com/questions/23329178/why-is-behavior-in-r-cmd-batch-different-for-optionserror-utilsdump-frames. Or we might adapt some parts from `purrr::safely()` or `purrr::possibly()`. (However, we should then clarify the intention of this exercise, as it formulated a bit inconcrete.)
  - [x] Nr. 2: Need to add good screenshots to the book, as .Rmd won't show the traceback natively.
    ![grafik](https://user-images.githubusercontent.com/11295192/50551247-fe652e80-0c7d-11e9-8757-7b2e689440bb.png)
  - [x] Nr. 3: Not solved yet.
  - [x] Nr. 4: @Tazinho Let's try to finalize this together.

- [x] All open points/exercises should now be reported explicitly under each bullet point above (maybe henningsway can solve one or the other, has a good idea for a new approach or has a more specific question to raise in an issue to Hadley. 

- [x] Assign Henningsway

@henningsway 
- [x] Read & edit all exercises.
- [x] Report any new points while updating the list above. 
- [x] Run a final spellcheck

@Tazinho and @henningsway 
- [x] Try to resolve any of the reported issues above.

**Comment by henningsway** [comment]
alright, I went through this Chapter and improved it as much as possible.

I think, there are three open issues. Maybe we can tackle them together @Tazinho ?
