### ISSUE TITLE
[Solve] "R6"-Chapter

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#130]
## [R6](https://advanced-r-solutions.rbind.io/r6.html)

- [x] sync exercises

### [Classes and methods](https://advanced-r-solutions.rbind.io/r6.html#classes-and-methods)
- [x] 1. Create a bank account R6 class that stores a balance and allows you to deposit and withdraw...
- [x] 2. Create an R6 class that represents a shuffled deck of cards. You should be able to draw cards...
- [ ] 3. Why can’t you model a bank account or a deck of cards with an S3 class?...
  - No idea... In theory one could simply use an environment or work with closures!?
  - status is "started" and I think this is ok
- [x] 4. Create an R6 class that allows you to get and set the current timezone. You can access the...
- [x] 5. Create an R6 class that manages the current working directory.It should have $get() and $set()...
- [ ] 6. Why can’t you model the time zone or current working directory with an S3 class?...
  - see above (the other S3 related exercise)...
- [x] 7. What base type are R6 objects built on top of? What attributes do they have?...

### [Classes and methods](https://advanced-r-solutions.rbind.io/r6.html#controlling-access)
- [x] 1. Create a bank account class that prevents you from directly setting the account balance, but you...
- [x] 2. Create a class with a write-only $password field. It should have $check_password(password)...
  - hm, would need to think a bit longer about this one...
- [x] 3. Extend the Rando class with another active binding that allows you to access the previous random...
  - hm, would need to reread about the Rando class possibly also solve the previous exercise first, to anser the additional question about the access.
- [x] 4. Can subclasses access private fields/methods from their parent? Perform an experiment to find...
  - simply need to try it out...(could also be advantageous to solve the other 2 exercises in this passage first)

### [Classes and methods](https://advanced-r-solutions.rbind.io/r6.html#reference-semantics)
- [x] 1. Create a class that allows you to write a line to a specified file. You should open a connection to...

**Comment by Tazinho** [comment]
## Prerequisites

```r
library(R6)
```

Create a bank account R6 class that stores a balance and allows you to deposit and withdraw money. Create a subclass that throws an error if you attempt to go into overdraft. Create another subclass that allows you to go into overdraft, but charges you a fee.

Let's start with a very basic bank account, similar to the `Accumulator` class in the text book.

```r
BankAccount <- R6Class("BankAccount",
                       list(
                         balance = 0,
                         deposit = function(dep = 0) {
                           self$balance = self$balance + dep
                           invisible(self)
                         },
                         withdraw = function(draw) {
                           self$balance = self$balance - draw
                           invisible(self)
                         }
                       ))

# Test
my_account <- BankAccount$new()
my_account$balance

my_account$
  deposit(5)$
  withdraw(2)$
  deposit(7)$
  balance
```

Now, lets make it more strict and add errors, that prevent a negative balance.

```r
BankAccountStrict <- R6Class("BankAccount",
                             inherit = BankAccount,
                             public = list(
                               withdraw = function(draw = 0) {
                                 if (self$balance - draw < 0) {
                                   stop("Your `withdraw` must be smaller ",
                                        "than your `balance`.")
                                 }
                                 super$withdraw(draw = draw)
                               }
                             ))

my_strict_account <- BankAccountStrict$new()
my_strict_account$balance

my_strict_account$
  deposit(5)$
  withdraw(2)$
  deposit(7)$
  withdraw(11)

my_strict_account$balance
```

Finally, we creat a class that charges a constant fee for each withdraw which leaves the account with a negative balance.

```
BankAccountCharging <- R6Class("BankAccount",
                               inherit = BankAccount,
                               public = list(
                                 withdraw = function(draw = 0) {
                                   if (self$balance - draw < 0) {
                                     draw = draw + 1
                                   }
                                   super$withdraw(draw = draw)
                                 }
                               ))

my_charging_account <- BankAccountCharging$new()
my_charging_account$balance

my_charging_account$
  deposit(5)$
  withdraw(2)$
  deposit(7)$
  withdraw(11)$
  withdraw(1)

my_charging_account$balance
```

**Comment by Tazinho** [comment]
2nd exercise:

Create an R6 class that represents a shuffled deck of cards. You should be able to draw cards from the deck with `$draw(n)`, and return all cards to the deck and reshuffle with `$reshuffle()`. Use the following code to make a vector of cards.

```r
suit <- c("♠", "♥", "♦", "♣")
value <- c("A", 2:10, "J", "Q", "K")
cards <- paste0(rep(value, 4), suit)
```

To keep the class flexible, we use `cards` as a field, which we provide as the default to the regarding methods.

```r
ShuffledDeck <- R6Class("ShuffledDeck",
                        public = list(
                          cards = {
                            suit <- c("♠", "♥", "♦", "♣")
                            value <- c("A", 2:10, "J", "Q", "K")
                            paste0(rep(value, 4), suit)
                          },
                          deck = NULL,
                          initialize = function(deck = cards) {
                            self$cards = deck
                            self$deck = sample(deck)
                          },
                          reshuffle = function(deck = self$cards) {
                            self$deck = sample(deck)
                            invisible(self)
                          },
                          draw = function(n){
                            output <- self$deck[seq_len(n)]
                            self$deck <- self$deck[-seq_len(n)]
                            output
                          }
                        ))

# Test
my_deck <- ShuffledDeck$new()
my_deck$draw(20)
my_deck$deck
my_deck$reshuffle()
my_deck$deck
```

**Comment by Tazinho** [comment]
4th exercise

Q: Create an R6 class that allows you to get and set the current timezone. You can access the current timezone with `Sys.timezone()` and set it with `Sys.setenv(TZ = "newtimezone")`. When setting the time zone, make sure the new time zone is in the list provided by `OlsonNames()`.

```r
TimeSetter <- R6Class("TimeSetter",
                      public = list(
                        get_timezone = Sys.timezone,
                        set_timezone = function(TZ, tzdir = NULL) {
                          stopifnot(TZ %in% as.character(OlsonNames(tzdir = tzdir)))
                          Sys.setenv(TZ = TZ)
                        }
                      )
)
                      
# Test
time_setter <- TimeSetter$new()

(old_tz <- time_setter$get_timezone())
time_setter$set_timezone("Antarctica/South_Pole")
time_setter$get_timezone()
time_setter$set_timezone(old_tz)
```

**Comment by Tazinho** [comment]
5th exercise

Create an R6 class that manages the current working directory. It should have $get() and $set() methods.

This `WDManager` class is quite simple, but should be easy to extend:

```r
WDManager <- R6Class("WDManager", 
                     list(
                       get = getwd,
                       set = setwd
                     ))
```

**Comment by Tazinho** [comment]
7th exercise:

What base type are R6 objects built on top of? What attributes do they have?

R6 objects are built on top of environments and have a `class` attribute, which is a character vector conatining the class name and the string `"R6"`.

**Comment by Tazinho** [comment]
exercise 2.1

```r
BankAccountStrict2 <- R6Class(
  "BankAccountStrict2",
  list(
    deposit = function(dep = 0) {
      private$balance = private$balance + dep
      invisible(self)
    },
    withdraw = function(draw = 0) {
      if (private$balance - draw < 0) {
        stop("Your `withdraw` must be smaller ",
             "than your `balance`.",
             call. = FALSE)
      }
      private$balance = private$balance - draw
      invisible(self)
    }
  ),
  private = list(balance = 0)
)

# Test
my_account_strict_2 <- BankAccountStrict2$new()
my_account_strict_2$balance

my_account_strict_2$deposit(5)
my_account_strict_2$withdraw(5)
my_account_strict_2$withdraw(1)
```

**Comment by henningsway** [comment]
wopwop!

**Comment by Tazinho** [comment]
my streak is about to end, getting tired...gn8
