### ISSUE TITLE
Collect all "Old Exercises" into single "Deprecated"-Chapter

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#135]
A couple of chapters have currently quite a few "old exercises" (solved and unsolved ones).

I think, it would be most helpful to have one Chapter, with all the deprecated Exercises. This Chapter could be structured in the same way as the book. (Starting with the foundations and so on)

This would give us and the readers a singe point to look for additional exercises.

**Comment by Tazinho** [comment]
Old exercises should be usually in the first version of the book.

In case the exercises are deprecated and not part of the first edition I think it's good to collect them, at least if we already solved them....Seems you already added a deprecated chapter. So, I think this should be closed here, as the process should be clear from now on...

**Comment by henningsway** [comment]
Generally, I think it would be nice to give convenient access to to some of the older exercises.
