### ISSUE TITLE
[Review] - "9. Functionals"-Chapter

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#138]
### [My first functional `map()`](https://advanced-r-solutions.rbind.io/functionals.html#my-first-functional-map)
- [x] 1. Use as_mapper() to explore how purrr generates anonymous functions for the integer, character...
- [x] 2. `map(1:3, ~ runif(2))` is a useful pattern for generating random numbers, but `map(1:3, runif(2))`...
- [ ] 3. Use the appropriate `map()` function to:...
- [ ] 4. The following code simulates the performance of a t-test for non-normal data. Extract the...
- [ ] 5. The following code uses a map nested inside another map to apply a function to every element...
- [ ] 6. Use map() to fit linear models to the mtcars using the formulas stored in this list...
- [ ] 7. Fit the model `mpg ~ disp` to each of the bootstrap replicates of mtcars in the list below, then...

### [Map variants](https://advanced-r-solutions.rbind.io/functionals.html#map-variants)
- [ ] 1. Explain the results of `modify(mtcars, 1)`...
- [ ] 2. Rewrite the following code to use `iwalk()` instead of `walk2()`. What are the advantages and ...
- [ ] 3. Explain how the following code transforms a data frame using functions stored in a list....
- [ ] 4. What does `write.csv()` return? i.e. what happens if you use it with `map2()` instead of `walk2()?`...

### [Predicate Functionals](https://advanced-r-solutions.rbind.io/functionals.html#predicate-functionals)
- [ ] 1. Why isn’t `is.na()` a predicate function? What base R function is closest to being a predicate...
- [ ] 2. `simple_reduce()` has a problem when `x` is length 0 or length 1. Describe the source of the ...
- [ ] 3. Implement the `span()` function from Haskell: given a list `x` and a predicate function f, span(x, f)...
- [ ] 4. Implement arg_max(). It should take a function and a vector of inputs, and return the elements...
- [ ] 5. The function below scales a vector so it falls in the range [0, 1]. How would you apply it to every 

### [Base Functionals](https://advanced-r-solutions.rbind.io/functionals.html#base-functionals)
- [ ] 1. How does apply() arrange the output? Read the documentation and perform some experiments....
- [ ] 2. What do eapply() and rapply() do? Does purrr have equivalents?...
- [ ] 3. Challenge: read about the fixed point algorithm. Complete the exercises using R....

**Comment by trannhatanh89** [comment]
I think the answer for Question 4 in 9.4 is a little bit confusing. I don't understand why `pluck()` is mentioned but not used in the example.

Q: The following code simulates the performance of a t-test for non-normal data. Extract the p-value from each test, then visualise.
```
trials <- map(1:100, ~ t.test(rpois(10, 10), rpois(7, 10)))
```

A: `pluck()` allows us to elegantly extract the p-values. We can then pass a data frame directly to `ggplot()` for the visualisation. For randomly generated data, we can expect a uniform distribution of the p-values.

```
library(ggplot2)

map_dbl(trials, "p.value") %>% 
  tibble::tibble(`p_value` = .) %>% 
  ggplot(aes(x = p_value, fill = p_value < 0.05)) + 
  geom_dotplot(binwidth = .025) +
  ggtitle("Distribution of p-values for random poisson data.")
```

**Comment by Tazinho** [comment]
@trannhatanh89 Thanks, good catch! Removed it now.
