### ISSUE TITLE
Move dependency-management from packrat to DESCRIPTION

### ISSUE THREAD

**Issue by hadley** [Tazinho/Advanced-R-Solutions#139]
This makes the repo extremely heavy, and I don't think it really adds anything to reproducibility.

You might want to use https://rtyley.github.io/bfg-repo-cleaner/ or similar to also remove from the history

**Comment by hadley** [comment]
In general, I find the use of packrat very frustrating, because the project `.Rprofile` overrides the user `.Rprofile` and none of my usual tools work.

**Comment by hadley** [comment]
Plus I think you can just rely on travis to ensure the book works with current versions of all packages

**Comment by hadley** [comment]
Instead, I'd recommend using a DESCRIPTION file that lists all of the needed packages.

**Comment by henningsway** [comment]
This sounds like a good idea, which we will embrance going forward.

So far, I removed the packrat-folder from the project, added a DESCRIPTION and changed the travis.yml accordingly (the book is building again).

I will later look how, we can reduce the reposize by deleting history and clean up the DESCRIPTION.

What would be the equivalent to `packrat::restore()` from here on?

**Comment by hadley** [comment]
`devtools::install_dev_deps()`

**Comment by henningsway** [comment]
I just cleaned up the Description and used BFG to to reduce the reposize (removed all files larger than 500K) things seem to be working ok.

@Tazinho @hadley please clone the repo again (and consider keeping the old one as a backup for a bit), so that we all start on the same page again.

fyi: I will split the book into two projects soon, which should further reduce the weight of the project, because numerous dependencies are only used for the first solution set.

**Comment by henningsway** [comment]
@hadley what equivalent would you recommend to maintain the DESCRIPTION?

I guess I'm looking for an replacement to `packrat::status()` to identify newly added as well as unused packages.

**Comment by hadley** [comment]
I just manually managed it with `usethis::use_package()`. You notice any absences very quickly because travis will fail

**Comment by henningsway** [comment]
The repo has a smaller scope (Edition 2) and a smaller size (removed packrat, cleaned history) than before. The DESCRIPTION still lists some packages, that are currently not needed anymore.

I will eventually clean this up in #143 and close here for now.

**Comment by hadley** [comment]
Nice, thanks!
