### ISSUE TITLE
before_chapter_script_1.R

### ISSUE THREAD

**Issue by hadley** [Tazinho/Advanced-R-Solutions#140]
Instead of using this approach, I'd recommend creating a `common.R` that every chapter sources

**Comment by hadley** [comment]
The annoyance with `before_chapter_script` is that the line numbers in errors are off, and it's easy to accidentally check in the file when it's in a state where the file is inlined into the chapter contents.

**Comment by henningsway** [comment]
Yes, the accidental committing of the contents of `before_chapter_scripte` within a chapter has happened to us a couple of times.
 
I've just added an non-included code chunk sourcing `before_chapter.R ` to all the chapters and the output seems fine with me.

Please reopen, if anything else needs to be done.
