### ISSUE TITLE
[Edit] - "S3"-Chapter

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#144]
### Basics
- [x] synced
- [x] edited/solved
- [x] 1st ex: not mentioned when each function gets called.
- [x] 4th ex: need to check if really a double or an integer is underlying the date class

### Classes
- [x] synced
- [x] edited/solved
- [x] 4th ex: C is written as capital letter!? Need to check if this makes sense here!?

### Generics and methods
- [x] 1st: List instead of lists.
- [x] 2nd: we need a point in the style guide explicitly stating how class names should be formatted. Here it is backticks, elsewhere it’s in quotes etc.
- [x] 3rd: Same as 2nd (formatting of class names)
- [x] 5th ex: reads very complex. Might be possible to simplify. Also not sure the final answer is correct.
- [ ] 6: Q: What are the arguments to [? Why is this a hard question to answer?...
  Didn't find a way to solve this completely.
- [x] synced
- [x] edited/solved

### Object styles
- [x] synced
- [x] edited
- [ ] _1. Categorise the objects returned by `lm()`, `factor()`, `table()`,..._
      Would be nice to briefly describe, how to arrive at these conclusions also.Let's check `ecdf()` and the naming of "other "again, I think it may be scalar.
  - @henningsway: Yes, it's added. Feel free to add explanations (I might do it myself when I have time...). I am also unsure about `table()`..., maybe we should look more detailed at the vecotrs pkg...
- [x] 2nd ex: comments need to start with capital letters usually.

### Inheritance
- [ ] 1st ex: Started, but not completed...(didn't look at it yet)
- [x] 2nd ex: answer doesn’t seem to solve the question.
- [x] 3rd ex: maybe it’s possible to give more information on .Class (need to inspect it experimentally first).
- [x] synced
- [x] edited

### Dispatch details
- [ ] 1st ex: Started, but not completed...
- [x] synced
- [x] edited
- [x] _2. What classes have a method for the `Math` group generic in base R? ...._
      I don't get the second last sentence. Let's try to improve this one.
  Also formatting needs to be improved.

### also
- [x] checked spelling

**Comment by henningsway** [comment]
Dear @Tazinho 
I edited the chapter, solved a couple of exercises along the way am quite happy with the result.

I think there are two open issues, which we should try to address. Other than that I think it is ready for review and I will go on and create the Review-Chapter.

**Comment by Tazinho** [comment]
@henningsway I tried to do my best in the short time and think it's quite good overall. Can you have a look at the remaining four started exercises. Maybe you have a good idea and provide me with some feedback. Otherwise I think it's already ready for review.

**Comment by henningsway** [comment]
Alright, let's close here then. (I think we'll have to leave to started messages open for now)

Also: please try to add the issue number to your commit messages, as it makes it easier to see what has happened in the meantime. :fist_right: :fist_left:
