### ISSUE TITLE
[Edit] - "Expressions"-Chapter

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#146]
## [Expressions](https://advanced-r-solutions.rbind.io/expressions.html)

@Tazinho 
- [x] Sync subsection names
- [x] Ensure that exercise numbers go 1,2,3,.. in each subsection.
- [x] Ensure linebreaks between Q & As
- [x] Sync the text and the order of all exercises in the chapter between Adv R and Adv R Solutions.

Read through all exercises. Edit them if possible and mark their correct status (green = "think this solution is correct", orange = "this solution is definitely not correct or sth. is missing". If sth. is missing, try to includede a todo). Also document open points within the following checklist:

### [Abstract syntax trees](https://advanced-r-solutions.rbind.io/expressions#abstract-syntax-trees)
- [x] 1. Reconstruct the code represented by the trees below: ...
- [x] 2. Draw the following trees by hand then check your answers with lobstr::ast(). ...
- [x] 3. What’s happening with the ASTs below? (Hint: carefully read ?"^") ...
- [x] 4. What is special about the AST below? (Hint: re-read Section 6.2.1) ...
- [x] 5. What does the call tree of an if statement with multiple else if conditions look like? Why? ...

### [Expressions](https://advanced-r-solutions.rbind.io/expressions.html#expressions)
- [x] 1. Which two of the six types of atomic vector can’t appear in an expression? Why? Similarly, why ...
* need to look again at it (probably just the formulations need to be revised)
- [x] 2. What happens when you subset a call object to remove the first element? e.g. ...
- [x] 3. Describe the differences between the following call objects. ...
* need to revisit and probably include a line of code as an example for the phrase "we can see that it is a generic"
- [x] 4. rlang::call_standardise() doesn’t work so well for the following calls. Why? What makes mean() special? ...
- [x] 5. Why does this code not make sense? ...
* maybe we can reformulate this solution with a nicer "flow"
- [x] 6. Construct the expression if(x > 1) "a" else "b" using multiple calls to call2(). How does the structure code reflect the structure of the AST? ...

### [Parsing and grammar](https://advanced-r-solutions.rbind.io/expressions.html#parsing-and-grammar)
- [x] 1. R uses parentheses in two slightly different ways as illustrated by these two calls: ...
- [ ] 2. = can also be used in two ways. Construct a simple example that shows both uses. ...
* Not sure if this way is a good solution. On the one hand I like the didactic intentions of this solution (how the process of finding the solution is showcased) but then I think there is still room for improvement for a more "mature/quality wording/structure". On the other hand I am not even sure if I like this "didactic" approach for this exercise so much. Would be happy if you (HB) or Hadley could have a look.
- [x] 3. Does -2^2 yield 4 or -4? Why? ...
- [x] 4. What does !1 + !1 return? Why? ...
* maybe can have a bit of a nicer flow.
- [x] 5. Why does x1 <- x2 <- x3 <- 0 work? Describe the two reasons. ...
- [x] 6. Compare the ASTs of x + y %+% z and x ^ y %+% z. What have you learned about the precedence of custom infix functions? ...
* answer is fine. But we should change the links to hard links...
- [x] 7. What happens if you call parse_expr() with a string that generates multiple expressions? e.g. parse_expr("x + 1; y + 1") ...
* answer is fine, but we should resolve the warning message
- [x] 8. What happens if you attempt to parse an invalid expression? e.g. "a +" or "f())". ...
- [x] 9. deparse() produces vectors when the input is long. For example, the following call produces a vector of length two: ...
- [x] 10. pairwise.t.test() assumes that deparse() always returns a length one character vector. Can ...

### [Walking the AST with recursive functions](https://advanced-r-solutions.rbind.io/expressions.html#walking-the-ast-with-recursive-functions)
- [x] 1. logical_abbr() returns TRUE for T(1, 2, 3). How could you modify logical_abbr_rec() so that ...
- [x] 2. logical_abbr() works with expressions. It currently fails when you give it a function. Why not? ...
- [x] 3. Modify find assignment to also detect assignment using replacement functions, i.e. names(x) <- ...
- [x] 4. Write a function that extracts all calls to a specified function. ...

- [x] All open points/exercises should now be reported explicitly under each bullet point above (maybe henningsway can solve one or the other, has a good idea for a new approach or has a more specific question to raise in an issue to Hadley. 

- [x] Assign Henningsway

@henningsway 
- [ ] Read & edit all exercises.
- [ ] Report any new points while updating the list above. 
- [ ] Run a final spellcheck

@Tazinho and @henningsway 
- [ ] Try to resolve any of the reported issues above.

**Comment by Tazinho** [comment]
@henningsway Only 7 exercises to edit here (rest is ok!). Hopefully I find some time soon. Otherwise feel free to jump in and close afterwards.

**Comment by Tazinho** [comment]
@henningsway 4 left here, can you take a look?

**Comment by Tazinho** [comment]
@henningsway Only one left, where I need you opinion/help.

**Comment by henningsway** [comment]
Puh, the parsing-2 question is really awkward, not so sure about a better example for `=`.

But, the other editing was fairly straightforward, I would say.
