### ISSUE TITLE
[Edit] - "Quasiquotation"-Chapter

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#147]
## [Quasiquotation](https://advanced-r-solutions.rbind.io/quasiquotation.html)

@Tazinho 
- [x] Sync subsection names
- [x] Ensure that exercise numbers go 1,2,3,.. in each subsection.
- [x] Ensure linebreaks between Q & As
- [x] Sync the text and the order of all exercises in the chapter between Adv R and Adv R Solutions.

Read through all exercises. Edit them if possible and mark their correct status (green = "think this solution is correct", orange = "this solution is definitely not correct or sth. is missing". If sth. is missing, try to includede a todo). Also document open points within the following checklist:

### [Motivation](https://advanced-r-solutions.rbind.io/quasiquotation.html#motivation)
- [x] 1. For each function in the following base R code, identify which arguments are quoted and which ...
* Still not happy with it (maybe it doesn't make sense to show all these error explicitly).
- [x] 2. For each function in the following tidyverse code, identify which arguments are quoted and ...
* this should be similarly clarified as the first exercise. Especially the dplyr parts. After reading there should be no open questions anymore.
### [Quoting](https://advanced-r-solutions.rbind.io/quasiquotation.html#quoting)
- [x] 1. How is expr() implemented? Look at its source code...
- [x] 2. Compare and contrast the following two functions. Can you predict the ouput before...
* not sure if the text relates enough to the exercise (or even what exactly the intention of the exercise is, besides memorizing the difference of the two functions!?)
- [x] 3. What happens if you try to use enexpr() with an expression (i.e. enexpr(x + y))?...
* is ok. But not sure if I am getting the sense of this exercise again.
- [x] 4. How are exprs(a) and exprs(a = ) different? Think abou...
- [x] 5. What are other differences between exprs() and alist()? Read the...
- [x] 6. The documentation for substitute() says: ...
* needs to be solved
### [Unquoting](https://advanced-r-solutions.rbind.io/quasiquotation.html#unquoting)
- [x] 1. Given the following components: ...
* needs introduction phrase
- [x] 2. The following two calls print the same, but are actually different... 
* seems like the functions in the exercise have changed to rlang. Need to check git history for this file. Maybe this helps to handle this faster.
### [Dot-dot-dot](https://advanced-r-solutions.rbind.io/quasiquotation.html#dot-dot-dot)
- [x] 1. One way to implement exec() is shown below. Describe...
- [ ] 2. Carefully read the source code for interaction(), expand.grid()...
* This question was a bit cumbersome, but it is at least "somehow solved" and the text is also not that good. Maybe you can improve a bit. If not, it is also ok. I am not sure if I missed sth here anyway.
- [x] 3. Explain the problem with this defintion of set_attr()...
* might be possible to minimal improve the reading flow in the beginning of the answer

### [Case studies](https://advanced-r-solutions.rbind.io/quasiquotation.html#case-studies)
- [ ] 1. In the linear-model example, we could replace the expr() in...
* needs to be finished. However, the suggested way in this exercise seems not to work !? (Instead it throws an error !?). Maybe you can try and report if it worked for you?
- [ ] 2. Re-implement the Box-Cox transform defined below using unquoting and...
* needs an introduction phrase
- [x] 3. Re-implement the simple compose() defined below using quasiquotation...

- [x] All open points/exercises should now be reported explicitly under each bullet point above (maybe henningsway can solve one or the other, has a good idea for a new approach or has a more specific question to raise in an issue to Hadley. 

- [x] Assign Henningsway

@henningsway 
- [ ] Read & edit all exercises.
- [ ] Report any new points while updating the list above. 
- [ ] Run a final spellcheck

@Tazinho and @henningsway 
- [ ] Try to resolve any of the reported issues above.

**Comment by Tazinho** [comment]
@henningsway I'll try to resolve the open ones, but regarding the time constraints I'd also be happy if you jump in earlier.

**Comment by Tazinho** [comment]
@henningsway It's yours now ;-)
