### ISSUE TITLE
Improve PDF Output

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#151]
We have a first PDF draft of this book, which is great. :tada: 

Let's use this issue to keep track of things thats (may) need to be improved:

- [x] think about Q & A Layout of Questions and Answers
- [x] avoid indentation for PDF (possibly keep it for HTML, but it's not so important anymore)
- [x] fix code to a reasonable width (69 character margin)
- [x] make sure code output doesn't leave the code-box to the right (even though the knitr option seems to be set correctly, this seems to happen on some occasions for now)
  - [x] Quasiquotation / Motivation / Q2: some overflow to the right for `dplyr::summarise_cols`-output
        (fixed by abbreviating and hardcoding the function source)
- [x] make sure plots do actually look good!
  - [x] Names and values / Copy-on-modify / Q4: include_graphics looks good
  - [x] Environemtns / Special environments / Q2: include_graphics looks good
  - [x] Functionals / My first funcitonal: map() / Q4: ggplot2 looks good
  - [x] Function Factories/ Graphical factories / Q2: 4 baseplots look good
  - [x] Function Factories/ Graphical factories / Q4: ggplot2 looks good
  - [x] S3 / Generics and methods / Q2: baseplot looks good
  - [x] S4 / Method dispatch / Q1 & Q2: include_graphics looks good
  - [x] Improving Performance / Vectorise / Q2 & Q3: ggplot looks good

**Comment by henningsway** [comment]
played around with `options(width =80)` in common.R today and also tried listings package as recommended in https://bookdown.org/yihui/rmarkdown-cookbook/text-width.html

Didn't work yet, we may have an issue here. Maybe we can copy what Hadley did in Advanced R :)

**Comment by hadley** [comment]
It looks like there are three key pieces:

* Set width option and knitr option: https://github.com/hadley/adv-r/blob/master/common.R#L29-L35 
* Hack knitr to wrap errors: https://github.com/hadley/adv-r/blob/master/common.R#L45-L65
* Make sure `str()` doesn't overflow: https://github.com/hadley/adv-r/blame/master/common.R#L26
