### ISSUE TITLE
Sync Exercises (again)

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#152]

**Comment by Tazinho** [comment]
@henningsway I am running into some issues with the csv for the exercise monitoring. Let's have a short call ASAP about it. 

In the meanwhile I am copy pasting the entries for the monitoring of the newly synched chapters here.

AST
1 solved
2 not solved
3 not solved
4 not solved
5 solved
Expressions
1 solved
2 not solved
3 not solved
4 solved
5 solved
6 started
Parsing and deparsing
1 solved
2 solved
3 not solved 
4 solved
5 started
6 solved
7 not solved
8 solved
9 not solved
10 not solved
Walking the AST with recursive functions
1 solved
2 solved
3 solved
4 solved

**Comment by henningsway** [comment]
I just opened the csv/tsv in libre office and was able to correct the missing tab-separators.
I hope, this fixes the issue. :)

**Comment by Tazinho** [comment]
Same for evaluation

Evaluation Basics
1 solved
2 solved
3 solved
4 started
5 solved

Quosures
1 solved
2 solved

Data Masks
1 solved
2 solved

Using tidy evaluation
1 started

Base evaluation
1 started
2 started
3 started

**Comment by Tazinho** [comment]
The csv is good now. All exercises from S3 on are resynched. Also the monitoring got resynched. I tried to be critical and when in doubt the status is orange rather than green (TODOS where added accordingly.)
