### ISSUE TITLE
[Edit] - "S4"-Chapter

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#156]
## [S4](https://advanced-r-solutions.rbind.io/s4.html)

@Tazinho 
- [x] Sync subsection names
- [x] Ensure that exercise numbers go 1,2,3,.. in each subsection.
- [x] Ensure linebreaks between Q & As
- [x] Sync the text and the order of all exercises in the chapter between Adv R and Adv R Solutions.

Read through all exercises. Edit them if possible and mark their correct status (green = "think this solution is correct", orange = "this solution is definitely not correct or sth. is missing". If sth. is missing, try to includede a todo). Also document open points within the following checklist:

### [Basics](https://advanced-r-solutions.rbind.io/s4#basics)
- [x] 1. lubridate::period() returns an S4 class. What slots does it have? What class is each slot? What...
- [x] 2. What other ways can you find help for a method? Read ?"?" and summarise the details...
  - needs a small overhaul. Maybe we should add a specific method as an example...

### [Classes](https://advanced-r-solutions.rbind.io/s4.html#classes)
- [x] 1. Extend the Person class with fields to match utils::person(). Think about what slots you will...
- [ ] 2. What happens if you define a new S4 class that doesn’t have any slots? (Hint: read about virtual...
 - looks like the exercise was misunderstood
- [x] 3. Imagine you were going to reimplement factors, dates, and data frames in S4. Sketch out the...
  - needs to be solved: factors and data.frames are missing.

### [Generics and methods](https://advanced-r-solutions.rbind.io/s4.html#generics-and-methods)
- [x] 1. Add age() accessors for the Person class....
  - started with the requirements
- [x] 2. The name is needed as the name of the generic as well as to explicitly incorporate method...
- [x] 3. Why does the show() method defined in Section 15.4.3 use is(object)[[1]]? (Hint: try printing ...
- [x] 4. What happens if you define a method with different argument names to the generic?...

### [Method dispatch](https://advanced-r-solutions.rbind.io/s4.html#method-dispatch)
- [x] 1. Draw the method graph for f(😅, 😽).
  - started (sketch of the solution should be easy quickly to draw)
- [x] 2. Draw the method graph for f(😃, 😉, 😙).
  - started (sketch of the solution should be easy quickly to draw)
- [x] 3. Take the last example which shows multiple dispatch over two classes that use multiple ...

### [S4 and S3](https://advanced-r-solutions.rbind.io/s4.html#s3-and-s4)
- [ ] 1. What would a full setOldClass() definition look like for an ordered factor (i.e. add slots and ...
  - would need to think through this a bit more...
- [x] 2. Define a length method for the Person class....

- [x] All open points/exercises should now be reported explicitly under each bullet point above (maybe henningsway can solve one or the other, has a good idea for a new approach or has a more specific question to raise in an issue to Hadley. 

- [x] Assign Henningsway

@henningsway 
- [x] Read & edit all exercises.
- [x] Report any new points while updating the list above. 
- [x] Run a final spellcheck

@Tazinho and @henningsway 
- [ ] Try to resolve any of the reported issues above.

**Comment by Tazinho** [comment]
@henningsway I think this one is also (mostly) ok now. Would be great if you can go on from here. (If you could do the 2 graphics, this would be awesome *liebguck* ;-)

**Comment by henningsway** [comment]
Will try my best very soon.

**Comment by henningsway** [comment]
did my part. Let's get hadleys feedback on the two open/started exercises and finalize afterwards.
