### ISSUE TITLE
[Edit] - "Measuring Performance"-Chapter

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#157]
## [Measuring performance](https://advanced-r-solutions.rbind.io/measuring-performance.html)

@Tazinho 
- [x] Sync subsection names
- [x] Ensure that exercise numbers go 1,2,3,.. in each subsection.
- [x] Ensure linebreaks between Q & As
- [x] Sync the text and the order of all exercises in the chapter between Adv R and Adv R Solutions.

Read through all exercises. Edit them if possible and mark their correct status (green = "think this solution is correct", orange = "this solution is definitely not correct or sth. is missing". If sth. is missing, try to includede a todo). Also document open points within the following checklist:

## Profiling
- [ ] 1. Profile the following function with torture = TRUE. What is surprising? Read the source code of 
  - no idea
  - Unfortunately I am getting the following error in the current profvis version whenever I use `torture = TRUE`: Error in stri_split_regex(string, pattern, n = n, simplify = simplify,  : 
  unimplemented type 'integer' in 'coerceToInteger'.

## Microbenchmarking
- [ ] 1. Instead of using bench::mark(), you could use the built-in function system.time(). But ...
  - Edited a bit. Pls have a look. The second part of the question is still unsolved.
- [ ] 2. Here are two other ways to compute the square root of a vector. Which do you think will be ...
  - started, but not really solved. We need to make assumptions on what we expect to be faster.
  - Also our current concludion doesn't actually correspond with the result of the benchmark. (See also comments/posts below)

- [x] All open points/exercises should now be reported explicitly under each bullet point above (maybe henningsway can solve one or the other, has a good idea for a new approach or has a more specific question to raise in an issue to Hadley. 

- [x] Assign Henningsway

@henningsway 
- [x] Read & edit all exercises.
- [x] Report any new points while updating the list above. 
- [x] Run a final spellcheck

@Tazinho and @henningsway 
- [ ] Try to resolve any of the reported issues above.

**Comment by Tazinho** [comment]
@henningsway: Can you confirm one of the outputs for the following code:

### Local output on my machine

On my local machine I get the following:

``` r
x <- runif(100)

bench::mark(sqrt(x),          # (1)
            x ^ 0.5,          # (2)
            x ^ (1 / 2),      # (3)
            exp(log(x) / 2),  # (4)
            relative = TRUE)[
              c("expression", "mean", "median", "total_time")
            ]
#> # A tibble: 4 x 4
#>   expression     mean median total_time
#>   <chr>         <dbl>  <dbl>      <dbl>
#> 1 sqrt(x)        1      1          1   
#> 2 x^0.5          4.97   6.80       4.97
#> 3 x^(1/2)        5.30   7.20       5.30
#> 4 exp(log(x)/2) 10.6   15.6       10.6
```

<sup>Created on 2019-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### Output in the book

However, this really differs to the result we get in the book. 

![grafik](https://user-images.githubusercontent.com/11295192/54923198-08f43480-4f0a-11e9-8a66-47b7cb596ecf.png)

**Comment by henningsway** [comment]
I think, this will be due to the hardware used in the travis pipeline. I'm ok, with the current output, what do you think?

**Comment by Tazinho** [comment]
> 
> 
> I think, this will be due to the hardware used in the travis pipeline. I'm ok, with the current output, what do you think?

I think it does matter, because the question is about what is the fastest method. Also the questions asks us to make some assumptions and (possibly) reason about the speed differences. As I really have no clue, a verified benchmark would be a good start for deeper thoughts.

**Comment by Tazinho** [comment]
@henningsway I am once through this. Not really satisfied with the result, but I have no further clues. Would be great I you cloud have a final look over it.

**Comment by henningsway** [comment]
I'm not so sure about these benchmarking exercises. I thought and googled a little bit, but I'm not yet sure what mechanisms precisely are at work here. Did a few minor edits, though. I think we should pass it to to Hadley and take it from there.
