### ISSUE TITLE
Spellcheck the whole book

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#16]
this can be done via rmarkdowns spellchecker. after #14 and #15 

- check every `
- check every codespace within `` and codeblocks if they have brackets
- make sure that chunks are in inconsolata font
- check code chunks. Handle intendier errors via chunk options instead of several workarounds...
- check that inline comments have 2 spaces in front
- check full stop after every sentence, also in front of code blocks (here mostly colons).

**Comment by Tazinho** [comment]
check every `
check every codepeace within `` and codeblocks if they have brackets

**Comment by Tazinho** [comment]
Make sure that chunks are in inconsolata font

**Comment by Tazinho** [comment]
Check Code chunks. Handle intendier errors via chunk options instead of several workarounds...

**Comment by Tazinho** [comment]
Also check that inline comments have 2 spaces in front

**Comment by henningsway** [comment]
started to collect multiple items in top comment

**Comment by Tazinho** [comment]
Moved to [Checklist for finalisation](https://github.com/Tazinho/Advanced-R-Solutions/issues/123)
