### ISSUE TITLE
Use semantic markup for questions

### ISSUE THREAD

**Issue by hadley** [Tazinho/Advanced-R-Solutions#162]
Instead of `__<span style="color:red">Q</span>__`, I'd recommend something like `[Q]{.Q}`, which you can then style appropriately using CSS for html, and a lua filter for latex.

**Comment by henningsway** [comment]
This sounds like a very good idea. Let's see, when we can tackle this @Tazinho .

(Btw. I was away for some time, but should be able to be around more consistently again)

**Comment by henningsway** [comment]
I took a look at this and familiarized myself with the concept of lua filters.
(https://ulyngs.github.io/blog/posts/2019-02-19-how-to-use-pandoc-filters-for-advanced-customisation-of-your-r-markdown-document/#solving-for-html)

I also set up a repo with a minimal example: https://github.com/henningsway/rmd_semantic_markup

Currently these open questions remain:
- how do I define a custom markup for an inline word sequence? I see how `{.Q}` can be used to refer to headers, but I didn't find a good resource/example explaining how to do this inline. (Which is what we want)
- I didn't really get the lua-Filter (taken from adv-r for now) to work. (Latex engine is set to xelatex)

**Comment by henningsway** [comment]
Added a question on Stackoverflow: https://stackoverflow.com/questions/56314272/create-output-agnostic-markup-for-fontcolor-in-rmarkdown-documents

**Comment by hadley** [comment]
You want a [custom span](https://pandoc.org/MANUAL.html#divs-and-spans).  How did you modify the lua filter? You'll need to turn `Div` into `Span`, probably

**Comment by henningsway** [comment]
Alright, thanks!

I think it's working properly for html now. Will cross the pdf-bridge, when we get to it. :)
