### ISSUE TITLE
Need to fix scale in graphic in Functionals ex 4

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#181]
https://advanced-r-solutions.rbind.io/functionals.html

Count shouldn't be between 0 and 1. However, the issue seems a little bit more tricky...
https://stackoverflow.com/questions/49330742/change-y-axis-of-dot-plot-to-reflect-actual-count-using-geom-dotplot

**Comment by henningsway** [comment]
apparently, this is the way it is intended: https://github.com/tidyverse/ggplot2/issues/2203#issuecomment-314944309

I would suggest converting the plot to a histogram then.

**Comment by Tazinho** [comment]
It‘s limited functionality in ggplot2 https://github.com/tidyverse/ggplot2/issues/2203 Id suggest to leave this open. As Id like to try to find a (readable) work around.

**Comment by henningsway** [comment]
Hey Malte,
i just had another look at the plot. I think it's fine the way it is. :)

I will close the issue again, please reopen and fix if you see the need.
