### ISSUE TITLE
[Edit] - "Rewriting R code in C++"-Chapter

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#184]
## Getting started with C++
- [ ] (opt) maybe add a little more prosaic explanation in addition to the C++-code.

## Missing values
- Rewrite any of the functions from the first exercise to deal with missing values...
  - [ ] (opt) for `cumsum()` it might make more sense in this exercise to remove `NA`s from the output.
  - [ ] (opt) Mention where to find the is_na methods. Also mention `is_na` from Rcpp sugar and Rcpp sugar in general (give reference to Rcpp sugar vignette and also to Advanced R first edition).

## Standard Template Library
- unique() using an unordered_set (challenge: do it in one line!).
  - [x] needs to address the challenge
- setdiff(), union(), and intersect() for integers using sorted ranges and set_union
  - [x] solution

**Comment by Tazinho** [comment]
@henningsway I think this is done for now (not really happy with this one again, but at least the exercises are solved except for the last one). Would be happy, if you could do the post editing.

**Comment by henningsway** [comment]
sounds good! good work, thanks. :)

**Comment by henningsway** [comment]
Hab es sprachlich geglättet. Mehr schaff ich gerade nicht. Von mir aus können wir dazu schon ein Review-Issue machen und die letzten Punkte dann beim Finalisen klären.

**Comment by Tazinho** [comment]
Super. Bin gerade nicht am Laptop, daher hier als Notiz: Klammern um First exercise müssen weg, but statt bur und its statt it‘s hatte ich noch iwo... mach gerne das Review issue :)
