### ISSUE TITLE
[Edit] - "Translating R Code"-Chapter

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#185]
## [Translating R Code](https://advanced-r-solutions.rbind.io/translating-r-code.html)

@Tazinho 
- [x] Sync subsection names
- [x] Ensure that exercise numbers go 1,2,3,.. in each subsection.
- [x] Ensure linebreaks between Q & As
- [x] Sync the text and the order of all exercises in the chapter between Adv R and Adv R Solutions.

Read through all exercises. Edit them if possible and mark their correct status (green = "think this solution is correct", orange = "this solution is definitely not correct or sth. is missing". If sth. is missing, try to includede a todo). Also document open points within the following checklist:

### [HTML](https://advanced-r-solutions.rbind.io/translating-r-code.html#html)
- [x] The escaping rules for <script> tags are different because they contain JavaScript...
- [x] The use of ... for all functions has some big downsides....
- [x] Reason about the following code that calls with_html() referening...
- [x] Currently the HTML doesn’t look terribly pretty, and it’s hard to see the structure...
### [LaTeX](https://advanced-r-solutions.rbind.io/translating-r-code.html#latex)
- [ ] Add escaping. The special symbols that should be escaped by adding a backslash
  - I am not sure where exactly it is ment to escape.
  - I am not sure where exactly the danger of double escaping lies in this exercise.
- [ ]  Complete the DSL to support all the functions that plotmath supports.
  - Not sure how to do the translations. If we go with the approach from the book, there are many special cases and pitfalls here, so I think I need to better understand the last exercise first, to tackle this one next.

- [x] All open points/exercises should now be reported explicitly under each bullet point above (maybe henningsway can solve one or the other, has a good idea for a new approach or has a more specific question to raise in an issue to Hadley. 

- [x] Assign Henningsway

@henningsway 
- [x] Read & edit all exercises.
- [x] Report any new points while updating the list above. 
- [x] Run a final spellcheck

@Tazinho and @henningsway 
- [ ] Try to resolve any of the reported issues above.

**Comment by henningsway** [comment]
Hey Malte,

ich bin jetzt einmal gründlich durch das Kapitel gegangen und hab einige Sätze umformuliert, ganz wenig Code aufgeräumt und die Rechtschreibung gefixed. Bei den offenen fachlichen Fragen im Latex-Teil kann ich gerade nicht viel sagen.

Kann dieses Issue geschlossen werden und das Review-Issue für Hadley entblockt werden? (Mach das ggf gerne. :))
