### ISSUE TITLE
Consistency in chapter 14 (R6 classes)

### ISSUE THREAD

**Issue by its-gazza** [Tazinho/Advanced-R-Solutions#211]
e.g. `BankAccount` class does not write `public` explicitly but `BankAccountStrct` does.  

I think it's better to explicitly write `public = list()` as users would then know which parameter is being used.

**Comment by its-gazza** [comment]
Sorry don't know how to do PR and link it to issue.  

PR here: https://github.com/Tazinho/Advanced-R-Solutions/pull/212

**Comment by henningsway** [comment]
I like it and we'll merge it! Thank you so much. (:
