### ISSUE TITLE
Note on format() may be obsolete?

### ISSUE THREAD

**Issue by MayaGans** [Tazinho/Advanced-R-Solutions#213]
After debugging the code in Exercise 3.6.8.1 I was trying to trace down the behavior below:

https://github.com/Tazinho/Advanced-R-Solutions/blob/1c92e81080f8c2a7f4aaca1cd4d81dffc61a5e0b/2-03-Vectors.Rmd#L331

And found:

- https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17548
- https://cran.r-project.org/doc/manuals/r-release/NEWS.html

So I think this bug has been addressed?

**Comment by henningsway** [comment]
Thank you so much Maya. :)

We hope to pick up work on this book soon and will have a look at this in more detail then.
