### ISSUE TITLE
Thoughts on 6.2.5.1

### ISSUE THREAD

**Issue by MayaGans** [Tazinho/Advanced-R-Solutions#214]
Hiya!

https://github.com/Tazinho/Advanced-R-Solutions/blob/b5c27c2f42bfee555816b3ef83815047f5ca6a87/06_Functions.Rmd#L19

I wasn't sure if you'd like this as an issue or PR (or at all) but figured since this is marked started I could take a stab at expanding on it? 🤷I was thinking you could add this blurb after the code chunk:

There isn't a 1 to 1 mapping between functions and names in R. Multiple names may point to the same function as we see for `f1`, `f2`, and `f3`. Also, each function has its own environment so it's possible that two functions might have the same "code" but are not the same because they have different environments (or closures). Lastly, anonymous functions don't have names so we'd have no way to look these up. 

TANGENT: We _could_ find the names of our functions if they are all in the global environment using `body(x) == body(y)`

```{r}
names(which(sapply(mget(lsf.str()), function(x) body(x) == body(function(x) (x - min(x)) / (max(x) - min(x))))))
```
....But that's just deparsing the body into a string and comparing the values. So if you want to think of two functions as being equal if their deparsed body strings as the same, then that's technically possible but that is just like searching for every variable that has the value of 5 [possible but not efficient]. 

The main point is that `name -> object` is a one way (non-unique) look up in R. There's no efficient way to go backwards. This is true for all values, not just functions.

Anyways, just a thought/rambling - hope it could be somewhat helpful!

**Comment by henningsway** [comment]
Thank you @MayaGans 

It seems clear now, but I didn't see it. I took your answer, edited it a little and added it to the book. :)
