### ISSUE TITLE
Improve Exercise 2.3.2

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#216]
The answer to exercise 2.3.4 can be a bit improved, so that it becomes easier to understand why we make the additional calculations and what the output means.

**Comment by henningsway** [comment]
Hab mir diese Aufgabe gerade angesehen. Liegt mir nicht so, auch weil ich nicht ganz genau verstanden habe wie die Objekt-Size mit den internen R-Funktionen zusammenhängt und wieso wir alle anderen R-Funktionen zusammenrechnen (und dabei overcounten können). Vllt fällt es dir ja leichter? :)
