### ISSUE TITLE
Answer to Exercise 11.2.1 is mistaken

### ISSUE THREAD

**Issue by Elucidase** [Tazinho/Advanced-R-Solutions#219]
I ran the code and found that `download.file %>% dot_every(10) %>% delay_by(0.1)` and `download.file %>% delay_by(0.1) %>% dot_every(10)` actually do the same thing: after each download the delay is made. This is expected: there is no mechanism in the code that enables the delay to know when the dot is printed.

**Comment by henningsway** [comment]
Thank you already, we'll check this soon!

**Comment by henningsway** [comment]
I just checked the solution and it was indeed incorrect. Thank you for bringing this to our attention. :)

Hopefully the new solution is better!
