### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#222]
- [x] 2 d: merge reviews (EDIT: 1 unreviewed exercise for Quasiquotation and 1 unreviewed exercise for Evaluation still need to be formulated as issues)
- [ ] 6-8 d: solve exercises
- [ ] 1 d: do a second review
- [ ] 2 d: write preface
- [ ] 2 d: finish

**Comment by henningsway** [comment]
Lass uns mal schauen, was mir mit diesem Issue machen. Entweder closen und durch andere Issues abbilden oder gerne auch updaten, damit es den jetztigen Arbeitsstand abbildet.

**Comment by Tazinho** [comment]
Wenn du magst, gerne updaten. Wenn du sonst Fragen hast, schreib einfach oder ruf kurz durch...

**Comment by henningsway** [comment]
ok, ich close es. ;) Habe beim Updaten gemerkt, dass es zu redundant mit unseren bisherigen issues ist.
