### ISSUE TITLE
Add Preface/Introduction

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#227]
## Preface (possibly Introduction)
- a little bit about this project
- what Advanced R meant for us
- our appreciation of open source and the R community :)
- possibly recommend introductory and alternative R/ programming books

## Conventions throughout the book
- reference to Adv R as „textbook“
- explain chapter enumeration
- conventions for style of names for objects, functions, classes, packages.
- adapt similar passage from Adv R
- mention R version
- explain implications of common.R
  - mention set.seed(1014) before every chapter
  - mention libraries (magrittr; parlmerpenguins, methods)

**Comment by henningsway** [comment]
So, bin einmal durch und gespannt auf dein Feedback. :)

**Comment by Tazinho** [comment]
All Fine. We only need to decide about the charity thing and then we can close here.
