### ISSUE TITLE
update with new advanced r version

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#24]
see here for the development version
http://adv-r.hadley.nz/

When the new version is available, we will change also the order of the solutions to match the new adv r version.

Excercises, which are not in the new version, will move to the appendix of the solutions book

Edit: Update Advanced R Version link to 2nd Edition, when we finished the exercises / review

**Comment by Tazinho** [comment]
The order and naming of the chapters in the 2nd Edition might not be final, but I don't think that too much will change. So, I will change the order to - Chapters of 2nd edition - testchapter - Chapters of 1st Edition. Everything that did not change will be copy pasted to have two complete editions in the end.

**Comment by Tazinho** [comment]
I would suggest to do this in the very end, since the whole structure of the book/2nd edition is currently evolving.

**Comment by henningsway** [comment]
Alright, let me close this for now then. We can pick editing and formating up, once we reached our content milestone.
