### ISSUE TITLE
misspellings 

### ISSUE THREAD

**Issue by arashHaratian** [Tazinho/Advanced-R-Solutions#242]
Hello.
As I read the book, I Found some spelling mistakes:
- Chapter 6, [beween](https://github.com/Tazinho/Advanced-R-Solutions/blob/ac34b7843c309a5dcac75058708035c3ad0a9d69/06_Functions.Rmd#L11) and [Whlie](https://github.com/Tazinho/Advanced-R-Solutions/blob/ac34b7843c309a5dcac75058708035c3ad0a9d69/06_Functions.Rmd#L23)
- Chapter 10, [funcitons](https://github.com/Tazinho/Advanced-R-Solutions/blob/ac34b7843c309a5dcac75058708035c3ad0a9d69/10_Function_factories.Rmd#L56) and [bahaviour](https://github.com/Tazinho/Advanced-R-Solutions/blob/ac34b7843c309a5dcac75058708035c3ad0a9d69/10_Function_factories.Rmd#L78)
- Chapter 13, [argurments](https://github.com/Tazinho/Advanced-R-Solutions/blob/ac34b7843c309a5dcac75058708035c3ad0a9d69/13_S3.Rmd#L353)
- Chapter 15, [cotains](https://github.com/Tazinho/Advanced-R-Solutions/blob/ac34b7843c309a5dcac75058708035c3ad0a9d69/15_S4.Rmd#L19)

**Comment by Tazinho** [comment]
Thanks a lot  @arashHaratian
