### ISSUE TITLE
Provide/rework final content (from prioritised list of remaining exercises)

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#254]
- [ ] Conditions 4.3: How would you modify the catch_cnds() defined if you wanted to recreate the original intermingling ...
  - It looks like we have written the exact same `catch_cnds` as already defined in Advanced R!? 
  - @hadley Did this change in Advanced R or did we somehow misinterprete the exercise? Strictly speaking, this exercise is not solved yet :(

---

- [ ] 24. Improving performance. 2.3 Can you make a faster version of table() for the case of an input of two integer vectors ...
  - HW: are you sure you need fastmatch here? I think you should be able to work out the bin with a little algebra
    - We can only think of the following alternative which is more readable, but slower (maybe we can put it in comments to help the reader)

    ```
    m <- matrix(1:pr, nrow = a_l, dimnames = dn)
    bin <- m[matrix(as.character(c(a, b)), ncol = 2)]
    ```

  - So, we think we need another hint on how to use some algebra to calculate the bin (faster).
  - We also still need to use the speed improvement for chi.squared downstream.

  - Answer from HW: Does this help?

    ```r
    x <- matrix(1:20, nrow = 4)
    (x - 1) %% 4 + 1
    (x - 1) %/% 4 + 1
    ```

  - @hadley Unfortunately I don't see it. 

---

- [ ] 9. Functionals: Explain how the following code transforms a data frame using functions stored in a list. ...
  - Wait for @Hadley to rename (or define) the `var` or the `nm` (see https://github.com/hadley/adv-r/issues/1655)

---

- [ ] 21. Translating R code. 2.2 Complete the DSL to support all the functions that plotmath supports. ...
  - @hadley we solved this one now. Please review :)

---

- [ ] 21. Environments 7.4.5.2 Draw a diagram that shows the enclosing environments of this function:....
  - we updated the solution and plan to update the diagram accordingly 
  - https://github.com/Tazinho/Advanced-R-Solutions/issues/244
  - @hadley please review. :)

----

- [ ] 13. S3. 5.1 How does [.Date support subclasses? How does it fail to support subclasses?
  - We don't fully understand this solution and would appreciate more context for motivation or an example for clarification
  - Are there any concrete implications for the user which result from the part about the internals? Maybe this would guide a bit on where to lay the focus while formulating this part.
  - We don't see why `mean()` is mentioned in the solution
  - Answer from HW: I think you can shrink the explanation of oldClass() a bit - just say that it's basically the same as class(), except that it doesn't return implicit classes, i.e. it's basically attr(x, "class") (looking at the C code that's exactly what it does, except that it also handles S4 objects).

    So if oldClass() is "basically" class, you can rewrite [.Date to make the implementation more clear:

    ```r
    `[.Date` <- function(x, ..., drop = TRUE) {
      out <- .Date(NextMethod("["), oldClass(x))
      class(out) <- class(x)
      out
    }
    ```

    So [.Date ensures that the output has the same class as in the input. But what about other attributes that a subclass might possess? They get lost:

    ```r
    x <- structure(1:4, test = "test", class = c("myDate", "Date"))
    attributes(x[1])
    ```

  - @hadley I think it's fine. One last review might be good though.

---

- [ ] Expressions: `logical_abbr()` works with expressions. It currently fails when you ...
  - we modified the solution a little bit
  - @hadley pls review :)

---

- [ ] 8. Conditions 2.3: Explain the results of running this code: ...
  - @hadley If you have any idea to make this clearer, pls do. We see that it's correct, but it's very hard to split this solution into smaller peaces to verify the statements.

---

**Comment by Tazinho** [comment]
@hadley Thanks for the advice in the other issue. We have now collected all outstanding solution improvements in this issue and probably work on it till short before deadline. We might therefore reach out for specific advice regarding some of the harder exercises.

However as we can't synch our working hours perfectly with the book, please be aware that we may need a little more help with the remaining exercises (probably a batch of exercises) at the very end.

**Comment by hadley** [comment]
Would you mind turning this into individual issues? It would make it easier for me to track/handle.

**Comment by hadley** [comment]
It would also be helpful if you could link each query to the source, since I look at this repo insufficiently frequently to remember where anything lives.

**Comment by Tazinho** [comment]
Sure, no problem. I hope it is more practical now.
