### ISSUE TITLE
Fix some small inconsistencies in PDF output/TOC

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#259]
- [x] There are too many empty pages in the beginning (I believe this came up adter adding the Bibliography)
- [x] There is a strange "<-" at the end of the TOC
  
![grafik](https://user-images.githubusercontent.com/11295192/103351429-7fd93c80-4aa3-11eb-886c-91fb88ee1e5e.png)

- [x] There is no "Bibliography" entry in the TOC (there is one in the print version of Advanced R)
- [[optional]] I am not sure if we really need References.Rmd. 
  - In HTML this is empty anyway and references are under each chapter instead
  - In PDF the References are under Bibliography which seems to be automatically generated and it would be interesting to check if this still holds, when we remove References.Rmd
  - On the other hand, it would be nice if we had a full references Section at the very end in the HTML version (In this way packages which are used in the book, but not explicitly references, e.g. data.table or caTools would also get some visibility)

**Comment by henningsway** [comment]
The -> is created by the last line of index.Rmd. For some strange reason the content of index.Rmd needs to be taken out prior to the compilation of the pdf. (This shouldn't be necessary, but somehow it is)

The bibliography is included via `\usepackage[nottoc]{tocbibind}`. It's not set as /backmatter but it should be fine for the pdf output.

Creating a working bibliography for the html is a task for another day. :)
