### ISSUE TITLE
Solve Conditions 4.3

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#262]
[Conditions 4.3](https://github.com/Tazinho/Advanced-R-Solutions/blob/main/08_Conditions.Rmd#L347)
How would you modify the catch_cnds() defined if you wanted to recreate the original intermingling ... 
  - It looks like we have written the exact same `catch_cnds` as already defined in Advanced R!? 
  - @hadley Did this change in Advanced R or did we somehow misinterprete the exercise? Strictly speaking, this exercise is not solved yet.

**Comment by hadley** [comment]
Hmmm, I guess I must've written `catch_cnds()` after I wrote that question? It certainly seems like `catch_cnds()` already preserves the order.

**Comment by Tazinho** [comment]
Yes, I also think that it wasn't there before. I [modified this a bit](https://github.com/Tazinho/Advanced-R-Solutions/commit/810802302a609401ec1edea2cd8cbf2e06ed925f) to explain the small inconsistency and think it's fine now.
