### ISSUE TITLE
Solve Improving Performance 2.3

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#263]
[Improving Performance 2.3](https://github.com/Tazinho/Advanced-R-Solutions/blob/main/24_Improving_performance.Rmd#L262)
Can you make a faster version of table() for the case of an input of two integer vectors ...
  - HW: are you sure you need fastmatch here? I think you should be able to work out the bin with a little algebra
    - We can only think of the following alternative which is more readable, but slower (maybe we can put it in comments to help the reader)

    ```
    m <- matrix(1:pr, nrow = a_l, dimnames = dn)
    bin <- m[matrix(as.character(c(a, b)), ncol = 2)]
    ```

  - So, we think we need another hint on how to use some algebra to calculate the bin (faster).
  - We also still need to use the speed improvement for chi.squared downstream.

  - Answer from HW: Does this help?

    ```r
    x <- matrix(1:20, nrow = 4)
    (x - 1) %% 4 + 1
    (x - 1) %/% 4 + 1
    ```

  - @hadley Unfortunately I don't see it.

**Comment by hadley** [comment]
Ok, looking at this closely now, I think I was fundamentally confused about what the result was supposed to look like. I can't see an obvious way to apply my hint or to make your code faster 😄

**Comment by Tazinho** [comment]
I'd always be interested in a faster solution for the one dimensional case no matter how it looks as I already tried quite a bit...see also https://twitter.com/malte_grosser/status/1263766820646989826. 

Anyway this is closed now, we can finally mark everything as finalized ☺️
