### ISSUE TITLE
Review Translating R code. 2.2

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#265]
[Translating R code. 2.2](https://github.com/Tazinho/Advanced-R-Solutions/blob/main/21_Translating_R_code.Rmd#L790)
Complete the DSL to support all the functions that plotmath supports. ...
  - @hadley we solved this one now. Please review :)

**Comment by hadley** [comment]
Made a few tweaks to the intro; otherwise looks fine.
