### ISSUE TITLE
Review Environments 7.4.5.2

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#266]
[Environments 7.4.5.2](https://github.com/Tazinho/Advanced-R-Solutions/blob/main/07_Environments.Rmd#L224)
Draw a diagram that shows the enclosing environments of this function:....
- we updated the solution and plan to update the diagram accordingly 
- https://github.com/Tazinho/Advanced-R-Solutions/issues/244
- @hadley please review. :)

**Comment by hadley** [comment]
Looks good to me! 

The only changes I'd consider are putting the environment containing f1 on the row of environments, and possibly flipping the diagram vertically so that you start with f1 on the left and work up to f3 on the right.

**Comment by henningsway** [comment]
Thank you for the review. I'm glad, we finally got this one right.

I just realized, that I didn't correctly save the source of the image. For that reason I will leave it as it currently is. :)
