### ISSUE TITLE
Review S3 5.1

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#267]
[S3. 5.1](https://github.com/Tazinho/Advanced-R-Solutions/blob/main/13_S3.Rmd#L542)
How does [.Date support subclasses? How does it fail to support subclasses?
  - We don't fully understand this solution and would appreciate more context for motivation or an example for clarification
  - Are there any concrete implications for the user which result from the part about the internals? Maybe this would guide a bit on where to lay the focus while formulating this part.
  - We don't see why `mean()` is mentioned in the solution
  - Answer from HW: I think you can shrink the explanation of oldClass() a bit - just say that it's basically the same as class(), except that it doesn't return implicit classes, i.e. it's basically attr(x, "class") (looking at the C code that's exactly what it does, except that it also handles S4 objects).

    So if oldClass() is "basically" class, you can rewrite [.Date to make the implementation more clear:

    ```r
    `[.Date` <- function(x, ..., drop = TRUE) {
      out <- .Date(NextMethod("["), oldClass(x))
      class(out) <- class(x)
      out
    }
    ```

    So [.Date ensures that the output has the same class as in the input. But what about other attributes that a subclass might possess? They get lost:

    ```r
    x <- structure(1:4, test = "test", class = c("myDate", "Date"))
    attributes(x[1])
    ```

  - @hadley I think it's fine. One last review might be good though.

**Comment by hadley** [comment]
The rewrite should look like:

```R
`[.Date` <- function(x, ..., drop = TRUE) {
  out <- .NextMethod("[")
  class(out) <- class(x)
  out
}
```

since the point is to eliminate the call to `.Date` 😄 

Otherwise, looks good!
