### ISSUE TITLE
Solve Conditions 2.3

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#268]
[Conditions 2.3](https://github.com/Tazinho/Advanced-R-Solutions/blob/main/08_Conditions.Rmd#L141)
Explain the results of running this code: ...
  - @hadley If you have any idea to make this clearer, pls do. We see that it's correct, but it's very hard to split this solution into smaller peaces to verify the statements.

**Comment by hadley** [comment]
Yeah, that seems fine to me — I've never managed to explain this particularly well. My only idea would be maybe that you could figure out some diagram to illustrate the bubbling more clearly. But likely to be a lot of work for relatively little gain.
