### ISSUE TITLE
Review Expressions exercise

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#269]
[Expressions](https://github.com/Tazinho/Advanced-R-Solutions/blob/main/18_Expressions.Rmd#L499)
`logical_abbr()` works with expressions. It currently fails when you give it a function. Why? How could you modify `logical_abbr()` to make it work? What components of a function will you need to recurse over?

  - we modified the solution a little bit
  - @hadley pls review :)

**Comment by hadley** [comment]
:+1:
