### ISSUE TITLE
Review the backpage

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#270]

**Comment by henningsway** [comment]
Did a review. Should be fine. :)

**Comment by Tazinho** [comment]
@hadley Can you also have a quick look on it. Mainly, I am just not sure if the wording for the bullet points about metaprogramming are 100% correct or if they contain any subtile mistakes.

The points are
*	How R parses expressions into elements of abstract syntax trees before it evaluates them
*	How you can modify these elements and their environments within this process
*	How to use this technique to create domain specific languages such as HTML or LaTeX

The current version of the backpage is under https://github.com/Tazinho/Advanced-R-Solutions/blob/main/000_backpage_new.Rmd

**Comment by hadley** [comment]
It feels a bit too long to me. I'd suggest something more like:

By working through the questions and answers in this book, you'll learn:
*	When R creates copies, and how it affects memory usage and code performance.
*	Everything you could ever want to know about functions.
*	The differences between calling and exiting handlers.
*	How to employ functional programming to solve modular tasks.
*	The motivation, mechanics, usage, and limitations of R's highly pragmatic S3 OO system.
*	The R6 OO system, which is more like OO programming in other languages.
*	The rules that R uses to parse and evaluate expressions.
*	How to use metaprogramming to generate HTML or LaTeX with elegant R code.
*	How to identify and resolve performance bottlenecks.

**Comment by Tazinho** [comment]
Yeah, that looks much nicer.

If we shorten it a bit more it would also allow us to add *short* autor bios. Without Bios we have 275 words (377 with the short ones I just included now). The backpage of Advanced R has 325 words. What do you think, Henning and Hadley?

**Comment by henningsway** [comment]
I really like it. :)
