### ISSUE TITLE
`mode<-` or `mode` ?

### ISSUE THREAD

**Issue by peterhurford** [Tazinho/Advanced-R-Solutions#32]
18.3.3 Exercises ("Expressions") #5 asks:

> How does `mode<-` work? How does it use `call()`?

[The solution given in our book](https://github.com/Tazinho/Advanced-R-Solutions/blob/master/11-Expressions.Rmd) annotates a particular function. However, it looks like the book annotates `mode`. It doesn't look like `mode` contains `call()`, though it does contain `"call"`.

I think we should be annotating `mode<-`, not `mode`. But `mode<-` also does not use `call` at all.

[The answer I gave in my repo](https://github.com/peterhurford/adv-r-book-solutions/blob/master/13_expressions/03_calls/exercise5.r) states:

> It dynamically creates a transformation function (e.g., `as.numeric`,`as.logical`, etc.) by using `paste0`, and then executes that by using `eval(call())` with that function and the item to be transformed.

The first part is accurate but it doesn't look like `mode<-` uses `eval(call())`. I thought maybe this is an R version problem, but @robertzk confirms `mode<-` in R 3.3 is still the same. I also can't find anything about it in [the R CHANGELOG](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html).

What am I missing?

**Comment by Tazinho** [comment]
Hm, if it is an R version related issue, it might be an idea to install a very early R version and just look it up from there, since the changelog might be not detailed enough. It should be a version very close to 2014, when the book was written. Otherwise I also have no idea atm.

**Comment by henningsway** [comment]
@peterhurford @Tazinho - What do we need to do here? What is the correct way to answer the question in 2018?

Please come forward with suggestions how to close this issue. :)

**Comment by henningsway** [comment]
Alright, I checked again and this seems to relate to expression exercise which is not in the 2nd Edition anymore: https://bookdown.org/Tazinho/Advanced-R-Solutions/expressions-1.html#names
