### ISSUE TITLE
Update repo to allow local building of book

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#36]
Goal:
Enable users and contributers which fork the project to directly build the book.

Next steps:
- [ ] locally recompile R 3.5.1 with `-enable-memory-profiling` so all exercises can be rendered
- [x] assure that book can be build directly after cloning https://github.com/henningsway/Advanced-R-Solutions
- [ ] eventually integrate with master of our main repository

**Comment by henningsway** [comment]
I forked the repo, cloned it and restored and updated packrat. I am still trying to get packrat to behave as I want it to.

Will try to get to a state, where I can render the book on my laptop first and move towards CI from there.
(possibly with a few subchapters first, when I keep running into problems.)

**Comment by henningsway** [comment]
@Tazinho could you please clone this repo and let me know if you can render index.Rmd?
(just open the index.Rmd and press `Ctrl + Shift + k` I believe)

**Comment by Tazinho** [comment]
Yes, it works. It doesn't open directly within the RStudion viewer.
However, we get the follwing:
Output created: _book/index.html
... and can view it afterwards manually in the browser.

**Comment by Tazinho** [comment]
Do you need any information from it? Otherwise I delete it...

**Comment by henningsway** [comment]
book builds locally and on Travis. Integration with this repo will be done in https://github.com/Tazinho/Advanced-R-Solutions/issues/67
