### ISSUE TITLE
Sort bookdown sidebar in a way similar to 2nd Ed of Adv R

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#43]
Hadley has started to include some "Parts" from `I` to `V` in his book. -> compare https://adv-r.hadley.nz/

I think it would be nice to find out how, these were created and to style our sidebar in a similar way.

**Comment by henningsway** [comment]
see: https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#special-headers

**Comment by Tazinho** [comment]
I have to look this up again. As I remember from the tidyverse cookbook the compiling process took a bit longer. If it is fast, I will add it soon. Otherwise, if it slows down, I will add it in the very end.

**Comment by henningsway** [comment]
solved this in https://github.com/henningsway/Advanced-R-Solutions/commit/055fac32191d6f95d8a7f0d240352ca38577b723
