### ISSUE TITLE
Update functions exercise 1 according the info provided in following link:

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#65]
https://github.com/hadley/adv-r/issues/800

**Comment by henningsway** [comment]
@Tazinho could you provide some more details, where this should be included in what kind of way?

**Comment by Tazinho** [comment]
It is a wrongly solved exercise, which we need to correct.

**Comment by henningsway** [comment]
sorry for the overhead, but could you specify the exercise and name the issue accordingly. Thanks!

**Comment by henningsway** [comment]
Do you think, that this is sth we want to do until next month?

**Comment by henningsway** [comment]
will close it, as it is represented in the issue above.
