### ISSUE TITLE
Develop Style Guide/Conventions

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#71]
moved to and merged with https://github.com/Tazinho/Advanced-R-Solutions/issues/123

**Comment by Tazinho** [comment]
Lets discuss ideas in the comments.
Lets put agreements via editing in Henning's starting post.

**Comment by henningsway** [comment]
I think it makes a lot of sense to tag `TODO` (and possibly also `QUESTION`s). @Tazinho could you provide a good example of how you want this to be used atm?

Ideas: 
- We could assign these TODOs to each other by `@taz`, `@hen`, `@pet`, `@rob` or `@all`.
- We could wrap TODOs in HTML comments `<!-- TODO: @all -->`. This keeps the book output "clean". Via Rstudio "Search in Files" for "`TODO.*@(hen|all)`"we can easily find open TODOs assigned to us.

**Comment by Tazinho** [comment]
I think I would place todos directly in front or behind the related content in the form: 
* ...content. TODO:
* or for code: `some code ... # TODO: `

In this way it is easy to see and search for in the book and in the source.

The only problem with HTML comments is that they are not visible in the book and I want to find them there. I don't think the book output is cleaner without them. I think there is sth (a comment) missing. (Also "search in files" can be slow in RStudio).

However, in general I don't want to restrict anyone from using any advanced features (when needed, pls use them). Just be aware that it can become very easy to loose track and you are responcible for your solutions, todos and so on.

I hope we can agree on this (for now).

**Comment by henningsway** [comment]
I think, we should use 80 characters per line.

- [ ] Also, what about using the `%>%`-pipe in base-R parts of the book?

**Comment by henningsway** [comment]
I feel, that we do not need to to "ban" the pipe. I feel, that in some cases it has almost become idiomatic for modern R and it is also discussed in Advanced R (https://adv-r.hadley.nz/functions.html#function-composition).

But I will try to avoid it in the base-R parts as good as I can. :)

**Comment by henningsway** [comment]
Code should not exceed 55characters. (Set margin in RStudio accordingly)

**Comment by henningsway** [comment]
avoid words like "easily" or "simply", as it can be discouraging for the reader.

**Comment by trannhatanh89** [comment]
Should small inconsistencies in term of coding styles be checked and corrected? For examples: `check.names=FALSE` (without spaces around =) vs. `check.names = FALSE` (with spaces).

**Comment by Tazinho** [comment]
Good question. I'd definitely appreciate any catches regarding the coding style (and will correct this one right now;). However, I am not sure if this might also be found via https://github.com/r-lib/styler in the very end.

**Comment by trannhatanh89** [comment]
Thank you. I will keep an eye out for such inconsistencies when reading your book, then, especially the ones not in a full code block.

**Comment by henningsway** [comment]
Just updated our Style Guide. Let's start to keep this in mind, while editing and also maintain it, if we find important missing aspects.

**Comment by henningsway** [comment]
merged with https://github.com/Tazinho/Advanced-R-Solutions/issues/123
