### ISSUE TITLE
Include also orange ("half solved") exercisese into our overview grafik

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#72]

**Comment by Tazinho** [comment]
Solved for now (see the orange box). Let me know if it's necessary to change more.

![grafik](https://user-images.githubusercontent.com/11295192/46531389-57027680-c89d-11e8-8268-26d0e6aa08d9.png)

**Comment by henningsway** [comment]
Good job, thank you!
