### ISSUE TITLE
Update AdvRSolutions to current state of AdvR (06.10.18)

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#74]
Process:
- capture state of 06.10.18
- check subsection titles for changes
- update exercises
  - add new ones
  - delete/  move old ones
- enumerate accordingly (1.,2.,3. instead of 1.,1.,1.,...)
- mark started exercises as orange and check if it has a todo
- add libraries to the start under prerequisities
- add indentation (3 spaces in front of text)

**Comment by Tazinho** [comment]
Progress:
- [x] Names and values
- [ ] bla
- [ ] bla
- [ ] bla

**Comment by henningsway** [comment]
current state of Adv R:https://github.com/hadley/adv-r/commit/82fe325b7ad838fbe643affc6431f438604f8f4d

**Comment by henningsway** [comment]
Thank you so much!
