### ISSUE TITLE
Where to get help (when solving exercises)

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#76]
When starting with an exercise a lot of things can be confusing. However, we already produced some content that might be easy to refactorize. Here is the place to collect any guidance on this topic.

* Old exercises:
  * Sometimes Hadley drops some exercises  or reformulates them. When we update the exercises in our book, we don't drop these exercises, but collect them at the bottom under a paragraph "old exercises". It might be really helpful to look there first. When you're lucky the exercise was already solved. (Note: exercises might also be moved between chapters)
  * Answers to the first edition of our book (look at the last chapters in our sidebar)
  * Answers from Roberts and Peters repository. We didn't merge the solutions completely so there might be a good chance that an exercise (or a very similar old one) is already solved.
* If you really have no idea (after some serious thinking):
  * Open an issue here. If you're eager also open an issue at @Hadley`s [Advanced R repo](https://github.com/hadley/adv-r/issues) and reference to the issue in our repo.
  * The same holds for exercises that you can answer but need to be improved on @Hadley's side.

**Comment by henningsway** [comment]
Hey @peterhurford @robertzk 
could you thumb this, so we know you've seen this. Would probably close this afterwards, as there is no todo otherwise. :)

**Comment by Tazinho** [comment]
Would u mind leaving it open? It’s important to keep an overview on that. (Maybe we can add a meta or PM tag?)

**Comment by henningsway** [comment]
alright for now, I might move it to the wiki some time. :)

**Comment by henningsway** [comment]
moved to https://github.com/Tazinho/Advanced-R-Solutions/wiki/Where-to-get-help-(when-solving-exercises)
