### ISSUE TITLE
Improve Exercise-Synchronisation between Advanced R and our Solutions

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#77]
The content and the exercises of Advanced R 2nd Ed are still changing (less and less), see https://github.com/hadley/adv-r/issues/1259

At the moment the process of checking for changes in Adv R and updating our book accordingly (e.g. https://github.com/Tazinho/Advanced-R-Solutions/issues/74) is manual and somewhat tedious, but doable.

We also need to update a list of open exercises (https://github.com/Tazinho/Advanced-R-Solutions/issues/73), when Adv R changes.

If anyone has a smart ideas, how to improve these processes, please sketch them out here.

**Comment by henningsway** [comment]
As Adv R II becomes more and more stable and you seem to have found a decent way to do this, I would be fine with closing this issue.

What do you think @Tazinho

**Comment by Tazinho** [comment]
I think the final chapters in Adv R II will be finished before we start solving them. So let's close here.
