### ISSUE TITLE
[Solve] - "Names and Values"-Chapter

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#79]
- https://advanced-r-solutions.rbind.io/names-and-values.html

### [Modify-in-place](https://bookdown.org/Tazinho/Advanced-R-Solutions/names-and-values.html#modify-in-place)
- [x] 1. Explain why the following code doesn’t create a circular list.

**Comment by henningsway** [comment]
found another open exercise, I believe

### [Copy-on-modify](https://bookdown.org/Tazinho/Advanced-R-Solutions/names-and-values.html#copy-on-modify)
[ ] 4. What happens when you run this code?

**Comment by henningsway** [comment]
Maybe work on feature branch and use clean commits like this: https://stackoverflow.com/questions/3697178/merge-all-changes-from-another-branch-as-a-single-commit

**Comment by henningsway** [comment]
will close this for now, knowing, that there is one exercise still unsolved and one that could probably be edited/improved.

**Comment by Tazinho** [comment]
Which one could be improved? I updated the obj_size(list(mean, sd, var)) exercise regarding Hadleys hint.

**Comment by henningsway** [comment]
number 3 in object sizes, I think. (see notes above)
