### ISSUE TITLE
Finish Exercises from "Vectors"-Chapter

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#80]
### [Atomic vectors](https://bookdown.org/Tazinho/Advanced-R-Solutions/vectors.html#atomic-vectors)
- [x] 1. How do you create scalars of type raw and complex? (See ?raw and ?complex)
- [x] 5. Precisely what do is.atomic(), is.numeric(), and is.vector() test for?

### [Attributes](https://bookdown.org/Tazinho/Advanced-R-Solutions/vectors.html#attributes)
- [x] 1. How is setNames() implemented? How is unname() implemented? Read the source code.
- [x] 2. What does dim() return when applied to a 1d vector? When might you use NROW() or NCOL()?

### [S3 atomic vectors](https://bookdown.org/Tazinho/Advanced-R-Solutions/vectors.html#s3-atomic-vectors)
- [x] 1. What sort of object does table() return? What is its type? What attributes does it have? How ...

### [Lists](https://bookdown.org/Tazinho/Advanced-R-Solutions/vectors.html#lists)
- [x] 1. List all the ways that a list differs from an atomic vector. 
- [x] 3. Compare and contrast c() and unlist() when combining a date and date-time into a single vector.

### [Data frames and tibbles](https://bookdown.org/Tazinho/Advanced-R-Solutions/vectors.html#data-frames-and-tibbles)
- [x] 2. What happens if you attempt to set rownames that are not unique?
- [x] 3. If df is a data frame, what can you say about t(df), and t(t(df))? Perform some ...

**Comment by Tazinho** [comment]
Finished 8 of 9 exercises. There is one exercise that I am basically too lazy for (dispatch of `c()` and behaviour of `unlist()` regarding concatenation of different date/datetime classes). 

I'd suggest that we do these another time and close here for now.

Instead we can think about a new task for me (environments? conditions? or functional programming part?)

**Comment by henningsway** [comment]
I think conditions is good, as we will be able to finish the first part. :)
