### ISSUE TITLE
32.1 incorrect solution?

### ISSUE THREAD

**Issue by svenhalvorson** [Tazinho/Advanced-R-Solutions#84]
Hey ya'll,

I appreciate you putting together solutions for this lovely book.

I don't think your solution to 32.1 is correct though. I believe we should be capturing the user input as part of the function like this:

```
is.expression_component <- function(x) {
  x = substitute(x)
  (is.atomic(x) & length(x) == 1) | is.call(x) | is.name(x) | is.pairlist(x)
}

```

The reason for this R will evaluate the input when you call `is.atomic(x)` making the call `is.expression_component(x <- 1)` return true because `is.atomic(x)` is true. It should return true because `is.call(x)` is true.

Let me know if you disagree!

**Comment by henningsway** [comment]
This does make sense to me. @peterhurford should we update accordingly?

**Comment by henningsway** [comment]
I agree and will change it now! :)
