### ISSUE TITLE
Update URL everywhere and Redirect from the old book to the new one

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#86]
- [x] Please add new url to repo

![image](https://user-images.githubusercontent.com/1403304/47939069-57b31a80-dee6-11e8-8a58-d6ac092a50ab.png)

- [x] also clearly deprecate content (and or redirect) on bookdown url.
  - plz also see https://github.com/rstudio/bookdown.org/pull/27#issuecomment-435640008

Thanks. :)

**Comment by Tazinho** [comment]
change URL on:
- [ ] github README
- [ ] maltes Website
- [ ] Hennings Website
- [ ] make a google search and try to contact everyone who hosts a wrong link

Redirect
- [ ] Redirect from the old bookdown automatically to the new domain

**Comment by henningsway** [comment]
if we had a javascript redirection, than the old links wouldn't be a big problem. :)

**Comment by henningsway** [comment]
alright, I think I'm done here. ;)

**Comment by henningsway** [comment]
Ok, I tried for some time, but I'm not getting the javascript to work correctly.
What about just creating a single page bookdown-project, that explains the migration and provides a link to click on?

Sounds alright? :)

**Comment by Tazinho** [comment]
Thanks Henning. I will also give it a try some time later. If it then doesn't work, I will directly go the way with the link.

**Comment by henningsway** [comment]
Also gave it another shot, i understood it a little better now.

If you create a simple bookdown page (with a link and eplanation) you can manually add the redirect functionality.

Just replace the `<body>`-tags in the *.html source of the `_book`-directory with `<body onload="window.location.replace('https://advanced-r-solutions.rbind.io/')">` and automatic redirects may take place. :)

**Comment by Tazinho** [comment]
That works, great. I added it to the index.html so that readers will be redirected to the new one instead.

Before we close here, what do we do with all the other pages (which might also be indexed by google already)? Should we delete everything in the old book apart from the starting page?

**Comment by Tazinho** [comment]
Perfect. Will do it later. (solving some exercises now :)

**Comment by henningsway** [comment]
I think the "redirect" - book should be as small as possible (no cover), so that the redirect happens fast.

It should contain a short explanation and a link though, in case the redirect doesn't work.

**Comment by henningsway** [comment]
Alright, let's close this some time soon. :)

**Comment by Tazinho** [comment]
Yep, will do it during the conditions part.

**Comment by henningsway** [comment]
let's close this. :)
