### ISSUE TITLE
[Solve] - "Conditions"-Chapter

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#89]
### [Signalling conditions](https://advanced-r-solutions.rbind.io/conditions.html#signalling-conditions)
- [ ] 2. What does the appendLF argument to message() do? How is it related to cat()?

### [Custom-conditions](https://advanced-r-solutions.rbind.io/conditions.html#custom-conditions)

- [x] 1. Inside a package, it’s occassionally useful to check that a package is installed before using it...
- [x] 2. Inside a package you often need to stop with an error when something is not right. Other ...

### [Applications](https://advanced-r-solutions.rbind.io/conditions.html#applications-1)

- [x] 1. Create suppressConditions() that works like suppressMessages() and supressWarnings() but ...
- [x] 2. Compare the following two implementations of message2error(). What is the main advantage of ...
- [x] 3. How would you modify the catch_cnds() defined if you wanted to recreate the original ...
- [x] 4. Why is catching interrupts dangerous? Run this code to find out. ...

**Comment by Tazinho** [comment]
Also related to conditions: The 2nd and 3rd exercise (remove.file and message/cat) are solved correctly but are not printed correct within the rmd code chunks..

**Comment by henningsway** [comment]
Very nice, Malte! :)

**Comment by Tazinho** [comment]
I think we can start the editing phase for this chapter as well. 4 exercises remain only partly or unsolved. However, I would suggest that we look at these after/during the editing phase together.

**Comment by henningsway** [comment]
I will close here. Let's handle the last remaining exercise in #124
