### ISSUE TITLE
[Review] - "Vectors"-Chapter

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#93]
### [Atomic vectors](https://advanced-r-solutions.rbind.io/vectors.html#atomic-vectors)

- [ ] 1. How do you create scalars of type raw and complex? (See ?raw and ?complex)...
- [ ] 2. Test your knowledge of vector coercion rules by predicting the output of the following...
- [ ] 3. Why is 1 == "1" true? Why is -1 < FALSE true? Why is "one" < 2 false?...
- [ ] 4. Why is the default missing value, NA, a logical vector? What’s special about logical...
- [ ] 5. Precisely what do is.atomic(), is.numeric(), and is.vector() test for?...

### [Attributes](https://advanced-r-solutions.rbind.io/vectors.html#attributes)

- [ ] 1. How is setNames() implemented? How is unname() implemented? Read the source...
- [ ] 2. What does dim() return when applied to a 1d vector? When might you use NROW() or...
- [ ] 3. How would you describe the following three objects? What makes them different to ...
- [ ] 4. An early draft used this code to illustrate structure():...

### [S3 atomic vectors](https://advanced-r-solutions.rbind.io/vectors.html#s3-atomic-vectors)

- [ ] 1. What sort of object does table() return? What is its type? What attributes does it ...
- [ ] 2. What happens to a factor when you modify its levels?...
- [ ] 3. What does this code do? How do f2 and f3 differ from f1?...

### [Lists](https://advanced-r-solutions.rbind.io/vectors.html#lists)

- [ ] 1. List all the ways that a list differs from an atomic vector....
- [ ] 2. Why do you need to use unlist() to convert a list to an atomic vector? Why doesn’t...
- [ ] 3. Compare and contrast c() and unlist() when combining a date and date-time into a ...

### [Data frames and tibbles](https://advanced-r-solutions.rbind.io/vectors.html#data-frames-and-tibbles)
- [ ] 1. Can you have a data frame with 0 rows? What about 0 columns?....
- [ ] 2. What happens if you attempt to set rownames that are not unique?...
- [ ] 3. If df is a data frame, what can you say about t(df), and t(t(df))? Perform...
- [ ] 4. What does as.matrix() do when applied to a data frame with columns of different ...

**Comment by henningsway** [comment]
I close this issue (and some of the related ones) for now, because we need to edit the chapter first. Will reopen once its "actionable". :)

**Comment by Tazinho** [comment]
@Hadley this one is ready review.
