### ISSUE TITLE
[Review] - "6. Functions"-Chapter

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#95]
### [Function fundamentals](https://advanced-r-solutions.rbind.io/functions.html#function-fundamentals)

- [ ] 1. Given name, like "mean", match.fun() lets you find a function...
- [ ] 2. It’s possible (although typically not useful) to call an anonymous...
- [ ] 3. A good rule of thumb is that an anonymous function should fit on one...
- [ ] 4. What function allows you to tell if an object is a function? What...
- [ ] 5. This code makes a list of all functions in the base package....
- [ ] 6. What are the three important components of a function?...
- [ ] 7. When does printing a function not show what environment it was...

### [Lexical Scoping](https://advanced-r-solutions.rbind.io/functions.html#lexical-scoping)

- [ ] 1. What does the following code return? Why? Describe how each of the...
- [ ] 2. What are the four principles that govern how R looks for values?...
- [ ] 3. What does the following function return? Make a prediction before...

### [Lazy evaluation](https://advanced-r-solutions.rbind.io/functions.html#lazy-evaluation)

- [ ] 1. What important property of && make x_ok() work?...
- [ ] 2. What does this function return? Why? Which principle does it ...
- [ ] 3. What does this function return? Why? Which principle does it ...
- [ ] 4. In hist(), the default value of xlim is range(breaks), the default ...
- [ ] 5. Explain why this function works. Why is it confusing?
- [ ] 6. How many arguments are required when calling library()?

### [... (dot-dot-dot)](https://advanced-r-solutions.rbind.io/functions.html#dot-dot-dot)

- [ ] 1. Explain the following results:...
- [ ] 2. In the following call, explain how to find the documentation for the....
- [ ] 3. Why does plot(1:10, col = "red") only colour the points, not the...

### [Exiting a function](https://advanced-r-solutions.rbind.io/functions.html#exiting-a-function)

- [ ] 1. What does load() return? Why don’t you normally see these...
- [ ] 2. What does write.table() return? What would be more useful?...
- [ ] 3. How does the chdir parameter of source() compare to...
- [ ] 4. Write a function that opens a graphics device, runs the supplied code...
- [ ] 5. We can use on.exit() to implement a simple version of ...

### [Function forms](https://advanced-r-solutions.rbind.io/functions.html#function-forms)

- [ ] 1. Rewrite the following code snippets into prefix form:...
- [ ] 2. Clarify the following list of odd function calls:...
- [ ] 3. Explain why the following code fails:...
- [ ] 4. Create a replacement function that modifies a random location in a...
- [ ] 5. Write your own version of + that will paste its inputs together if they...
- [ ] 6. Create a list of all the replacement functions found in the base ...
- [ ] 7. What are valid names for user-created infix functions?...
- [ ] 8. Create an infix xor() operator....
- [ ] 9. Create infix versions of the set functions intersect(), union(), ...

**Comment by henningsway** [comment]
@hadley, this (big) one should also be ready to be looked through.
