### ISSUE TITLE
Testissue for Chapter-Progress

### ISSUE THREAD

**Issue by henningsway** [Tazinho/Advanced-R-Solutions#98]
An idea (not really sure about this)

## Subheading 1
- Question 1
    - [ ] solved
    - [ ] reviewed
    - [ ] approved
    - [ ] proof-read
    - [ ] done
- Question 2
    - [ ] solved
    - [ ] reviewed
    - [ ] approved
    - [ ] proof-read
    - [ ] done

OR

## Subheading 1
- [ ] [review] Question 1
- [ ] [approved] Question 2
- [x] [done] Question 3

**Comment by Tazinho** [comment]
Also not sure. However from these two I would prefer the first.
Can you give a short description behind each point - how one comes from one stage into the other one and also who does each step?

**Comment by henningsway** [comment]
alright, we just agreed on creating seperate issues on chapter level for each step.
