### ISSUE TITLE
[Edit] - "Vectors"-Chapter

### ISSUE THREAD

**Issue by Tazinho** [Tazinho/Advanced-R-Solutions#99]
@Tazinho 
- [x] Sync the text and the order of all exercises in the chapter between Adv R and Adv R Solutions.

Read through all exercises. Edit them if possible and mark their correct status (green = "think this solution is correct", orange = "this solution is definitely not correct or sth. is missing". If sth. is missing, try to includede a todo). Also document open points within the following checklist:
- [x] [Atomic vectors](https://advanced-r-solutions.rbind.io/vectors.html#atomic-vectors). 
  - [x] Nr. 3: is ASCII-order really relevant here?
Hmm...maybe not ASCII, but I have difficulties to understand the concrete process, see `?Comparison`. Can you? Here is the output from help:
> Comparison of strings in character vectors is lexicographic within the strings using the collating sequence of the locale in use: see locales. The collating sequence of locales such as en_US is normally different from C (which should use ASCII) and can be surprising. Beware of making any assumptions about the collation order: e.g. in Estonian Z comes between S and T, and collation is not necessarily character-by-character – in Danish aa sorts as a single letter, after z. In Welsh ng may or may not be a single sorting unit: if it is it follows g. Some platforms may not respect the locale and always sort in numerical order of the bytes in an 8-bit locale, or in Unicode code-point order for a UTF-8 locale (and may not sort in the same order for the same language in different character sets). Collation of non-letters (spaces, punctuation signs, hyphens, fractions and so on) is even more problematic.

> Character strings can be compared with different marked encodings (see Encoding): they are translated to UTF-8 before comparison.

  - [x] Nr. 5: The alignment of the 3 functions as bullet points could be better. This could be achieved by a short introduction sentence. No good idea so far.
- [x] [Attributes](https://advanced-r-solutions.rbind.io/vectors.html#attributes)
  - [x] Nr. 1: Not sure if we need "the note" in the `unname()` part at all.
  - [x] Nr. 2: Not sure, if this could be formulated more clear/easy.
- [x] [S3 atomic vectors](https://advanced-r-solutions.rbind.io/vectors.html#s3-atomic-vectors)
- [x] [Lists](https://advanced-r-solutions.rbind.io/vectors.html#lists)
  - [x] Nr. 1: Same issue as above. The exercise should start with a short sentence as the alignment would look better when the first line is not empty.
  - [x] Nr. 3: I am not getting what you mean in the sentence previous to the last on (the one in bracktes). When you clarify this sentence appropriate, then this exercise is fine from my side.
- [x] [Data frames and tibbles](https://advanced-r-solutions.rbind.io/vectors.html#data-frames-and-tibbles)
  - [x] check output of first dataframe/ tibble - exercise

- [x] All open points/exercises should now be reported explicitly under each bullet point above (maybe henningsway can solve one or the other, has a good idea for a new approach or has a more specific question to raise in an issue to Hadley. 
- [x] Assign Henningsway

@henningsway 
- [x] Read & edit all exercises.
- [x] Report any new points while updating the list above. 
- [x] Run a final spellcheck
- [x] check Maltes comments in this thread also

@Tazinho and @henningsway

**Comment by henningsway** [comment]
> Same procedure as with the first chapter.
> Maybe we can think of a clear workflow.
> However, both of us should read through the chapter once and edit / post open questions in this issue.

yes, this is a very good idea. I will edit, your post now. Let's keep an overview of what is left to do in this first comment.

**Comment by Tazinho** [comment]
I assigned you, since I read it once, but of course I will also still work on further editing and reviewing here :)

**Comment by Tazinho** [comment]
@henningsway I would like to give this chapter to you now :)

**Comment by henningsway** [comment]
seems done to me (for now)

https://github.com/Tazinho/Advanced-R-Solutions/commit/cb6995690f2f796d61b1e128d14d54b6499f4276

**Comment by Tazinho** [comment]
Some small notes (i will change later)
- in the table exercise factors need to be mentioned
- old exercises might also be from earlier stages Adv R II. In the end we will delete these subsections.

**Comment by Tazinho** [comment]
@henningsway Can you look once more over my commit? I am not sure about the wording ("respectively factor levels"). I am missing sth. for "beziehungsweise". The issue is that for factor variables in data frames the levels of the factors and not only the appearing values are important for the dimension of the table.

Afterwards please close :)
